# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import os
import pathlib
import typing

class BatchProcessor:
    r"""
    Bounded native worker pool for stable identities of independent files.
    
    Durable orchestration, publication, and cleanup remain Python service
    responsibilities. This class owns only a private Rayon pool and performs
    immutable, fail-closed reads.
    """
    worker_count: int
    def __new__(cls,worker_count:int): ...
    def stable_file_identities(self, paths,chunk_size = ...) -> list[tuple[int, int, str]]:
        ...


def build_expected_frame_records(frame_count: int, ext: str = ...) -> list[tuple[int, str]]:
    ...

def build_frame_records(paths: list[str], *, relative_to: str | None = ..., zero_based: bool = ...) -> list[tuple[int, str]]:
    ...

def copy_file_descriptor_to_path(source_fd: int, target_path: pathlib.Path, chunk_size: int = ...) -> int:
    ...

def decrypt_encrypted_file_range(path: pathlib.Path, master_key: bytes, start: int, end: int) -> bytes:
    ...

def derive_anonymization_status(processing_error: bool, anonymization_validated: bool, sensitive_meta_processed: bool, frames_extracted: bool, anonymized: bool, was_created: bool, processing_started: bool) -> str:
    ...

def derive_frame_annotation_status(has_state: bool, frames_extracted: bool, initial_prediction_completed: bool, lvs_created: bool, frame_annotations_generated: bool) -> str:
    ...

def derive_hls_publication_action(attempt_status: str, owner_matches: bool, has_active_lease: bool, has_ready_generation: bool) -> str:
    ...

def derive_hls_reconciliation_action(status: str, is_stale: bool) -> str:
    ...

def derive_hls_reservation_action(active_status: str, active_is_stale: bool, ready_matches_source: bool, force: bool) -> str:
    ...

def derive_report_anonymization_status(processing_error: bool, anonymization_validated: bool, sensitive_meta_processed: bool, anonymized: bool, processing_started: bool) -> str:
    ...

def derive_segment_annotation_status(segment_annotations_created: bool, segment_annotations_validated: bool, outside_segments_removed: bool) -> str:
    ...

def encryption_status(path: pathlib.Path) -> str:
    ...

def is_lx_encrypted_file(path: pathlib.Path) -> bool:
    ...

def native_capabilities() -> list[tuple[str, str, str]]:
    ...

def normalize_frame_sampling_strategy_token(value: str) -> str:
    ...

def normalize_frame_task_mode_token(value: str) -> str:
    ...

def parse_extracted_frame_numbers(paths: list[str]) -> list[int]:
    ...

def render_single_page_pdf(text: str) -> bytes:
    ...

def sha256_file_hex(path: pathlib.Path, chunk_size: int = ...) -> str:
    ...

def stable_file_identity(path: pathlib.Path, chunk_size: int = ...) -> tuple[int, int, str]:
    ...

def stable_snapshot_to_path(source_path: pathlib.Path, target_path: pathlib.Path, chunk_size: int = ...) -> tuple[int, int, str]:
    ...

def storage_profile_policy_rows() -> list[tuple[str, str, str]]:
    ...

