from __future__ import annotations

from .ai import extract_text_from_video_frames, predict_video
from .anonymization import (
    anonymize_video_file,
    censor_outside_video_frames,
    cleanup_video_raw_assets,
    create_anonymized_video_frame_files,
    merge_outside_frame_intervals,
    rebuild_processed_video_without_outside_frames,
)
from .frames import (
    bulk_create_video_frames,
    create_video_frame_object,
    delete_video_frame_range,
    delete_video_frames,
    extract_video_frame_range,
    extract_video_frames,
    get_video_frame,
    get_video_frame_number,
    get_video_frame_path,
    get_video_frame_paths,
    get_video_frame_range,
    get_video_frames,
    initialize_video_frames,
)
from .imports import (
    create_initialized_video_file_from_path,
    create_video_file_from_path,
    initialize_video_file,
)
from .io import (
    delete_video_with_owned_files,
    ensure_local_processed_video_file,
    ensure_local_raw_video_file,
    get_processed_video_file_path,
    get_processed_video_stream_path,
    get_raw_video_file_path,
    get_raw_video_stream_path,
    get_target_anonymized_video_path,
    get_temp_anonymized_video_frame_dir,
    get_video_base_frame_dir,
    get_video_frame_dir_path,
    set_video_frame_dir,
)
from .metadata import (
    ensure_default_video_fps,
    get_video_crop_template,
    get_video_duration,
    get_video_endo_roi,
    get_video_ffmpeg_meta,
    get_video_fps,
    get_video_import_context_names,
    get_video_import_processor,
    initialize_video_specs,
    update_video_meta,
    update_video_text_metadata,
    video_frame_number_to_seconds,
)
from .queries import (
    count_unmodified_other_videos,
    get_all_videos,
    get_video_by_content_hash,
    get_video_by_pk,
    video_hash_exists,
)
from .segments import get_video_outside_segments
from .state import get_or_create_video_state
from .streaming import (
    can_offload_video_stream,
    get_active_raw_video_file,
    get_active_raw_video_file_url,
    get_active_video_file,
    get_active_video_file_path,
    get_active_video_file_url,
    get_processed_video_stream_relative_path,
    get_protected_video_stream_url,
    get_raw_video_stream_relative_path,
    get_video_stream_relative_path,
    is_encrypted_streamable_video_path,
    resolve_video_stream_source,
)
from .types import VideoArtifactKind, parse_video_artifact_kind
from .validation import validate_video_metadata_annotation

__all__ = [
    "VideoArtifactKind",
    "anonymize_video_file",
    "bulk_create_video_frames",
    "can_offload_video_stream",
    "censor_outside_video_frames",
    "cleanup_video_raw_assets",
    "count_unmodified_other_videos",
    "create_anonymized_video_frame_files",
    "create_initialized_video_file_from_path",
    "create_video_file_from_path",
    "create_video_frame_object",
    "delete_video_frame_range",
    "delete_video_frames",
    "delete_video_with_owned_files",
    "ensure_default_video_fps",
    "ensure_local_processed_video_file",
    "ensure_local_raw_video_file",
    "extract_text_from_video_frames",
    "extract_video_frame_range",
    "extract_video_frames",
    "get_active_raw_video_file",
    "get_active_raw_video_file_url",
    "get_active_video_file",
    "get_active_video_file_path",
    "get_active_video_file_url",
    "get_all_videos",
    "get_or_create_video_state",
    "get_processed_video_file_path",
    "get_processed_video_stream_path",
    "get_processed_video_stream_relative_path",
    "get_protected_video_stream_url",
    "get_raw_video_file_path",
    "get_raw_video_stream_path",
    "get_raw_video_stream_relative_path",
    "get_target_anonymized_video_path",
    "get_temp_anonymized_video_frame_dir",
    "get_video_base_frame_dir",
    "get_video_by_content_hash",
    "get_video_by_pk",
    "get_video_crop_template",
    "get_video_duration",
    "get_video_endo_roi",
    "get_video_ffmpeg_meta",
    "get_video_fps",
    "get_video_frame",
    "get_video_frame_dir_path",
    "get_video_frame_number",
    "get_video_frame_path",
    "get_video_frame_paths",
    "get_video_frame_range",
    "get_video_frames",
    "get_video_import_context_names",
    "get_video_import_processor",
    "get_video_outside_segments",
    "get_video_stream_relative_path",
    "initialize_video_file",
    "initialize_video_frames",
    "initialize_video_specs",
    "is_encrypted_streamable_video_path",
    "merge_outside_frame_intervals",
    "parse_video_artifact_kind",
    "predict_video",
    "rebuild_processed_video_without_outside_frames",
    "resolve_video_stream_source",
    "set_video_frame_dir",
    "update_video_meta",
    "update_video_text_metadata",
    "validate_video_metadata_annotation",
    "video_frame_number_to_seconds",
    "video_hash_exists",
]
