# Generated by Django 5.1.3 on 2024-11-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_patientexaminationindication_indication_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationindication',
            name='examination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='endoreg_db.examination'),
            preserve_default=False,
        ),
    ]
