# Generated by Django 5.1.3 on 2024-11-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_endoscope_center_endoscope_endoscopy_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endoscope',
            old_name='endoscopy_type',
            new_name='endoscope_type',
        ),
        migrations.AddField(
            model_name='endoscope',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endoscope',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
