from __future__ import annotations

from endoreg_db.utils.core.translation import build_multilingual_response

from .anonymization import (
    AnonymizationOverviewView,
    AnonymizationValidateView,
    anonymization_current,
    anonymization_status,
    start_anonymization,
)
from .auth import keycloak_callback, keycloak_login, public_home
from .examination import (
    ExaminationManifestCache,
    ExaminationViewSet,
    get_classification_choices_for_examination,
    get_classifications_for_examination,
    get_findings_for_examination,
    get_indication_choices,
    get_indications_for_examination,
    get_instruments_for_examination,
    get_interventions_for_examination,
    get_location_classification_choices_for_examination,
    get_location_classifications_for_examination,
    get_morphology_classification_choices_for_examination,
    get_morphology_classifications_for_examination,
)
from .finding import (
    FindingViewSet,
    get_classifications_for_finding,
    get_interventions_for_finding,
)
from .finding_classification import (
    FindingClassificationViewSet,
    get_classification_choices,
    get_location_choices,
    get_morphology_choices,
)
from .media import (
    get_sensitive_metadata_pk,
    label_list,
    pdf_sensitive_metadata,
    pdf_sensitive_metadata_list,
    pdf_sensitive_metadata_verify,
    sensitive_metadata_list,
    video_sensitive_metadata,
    video_sensitive_metadata_verify,
)
from .misc import (
    AuditLedgerIntegrityStatusView,
    CenterViewSet,
    ExaminationStatsView,
    GenderViewSet,
    GeneralStatsView,
    SensitiveMetaStatsView,
    UploadFileView,
    UploadStatusView,
    VideoSegmentStatsView,
    application_settings_ai_dataset_attachments,
    application_settings_ai_dataset_export,
    application_settings_ai_dataset_export_download,
    application_settings_ai_dataset_frame_bucket_distribution,
    application_settings_ai_dataset_training_manifest,
    application_settings_ai_datasets_dropdown,
    application_settings_annotators_dropdown,
    application_settings_centers_dropdown,
    application_settings_detail,
    application_settings_backup,
    application_settings_model_training_options,
    application_settings_model_training_run_detail,
    application_settings_model_training_runs,
    application_settings_network_node_detail,
    application_settings_network_node_roles_dropdown,
    application_settings_network_nodes,
    application_settings_processors_dropdown,
    application_settings_report_templates_dropdown,
    application_settings_video_dimension_backfill_run_detail,
    application_settings_video_dimension_backfill_runs,
    csrf_token_view,
)
from .patient import PatientViewSet
from .patient_examination import (
    ExaminationCreateView,
    PatientExaminationDetailView,
    PatientExaminationListView,
    PatientExaminationViewSet,
)
from .patient_finding import OptimizedPatientFindingViewSet, PatientFindingViewSet
from .patient_finding_classification import create_patient_finding_classification
from .report import (
    PatientExaminationReportViewSet,
    ReportLlmJobStatusView,
    ReportReimportView,
    ReportStreamView,
)
from .video import (
    VideoApplyMaskView,
    VideoCorrectionView,
    VideoExaminationViewSet,
    VideoReimportView,
    VideoRemoveFramesView,
    VideoStreamView,
)

__all__ = [
    "anonymization_status",
    "anonymization_current",
    "start_anonymization",
    "AnonymizationOverviewView",
    "AnonymizationValidateView",
    "keycloak_login",
    "keycloak_callback",
    "public_home",
    "ExaminationManifestCache",
    "ExaminationViewSet",
    "get_classification_choices_for_examination",
    "get_morphology_classification_choices_for_examination",
    "get_location_classification_choices_for_examination",
    "get_classifications_for_examination",
    "get_location_classifications_for_examination",
    "get_morphology_classifications_for_examination",
    "get_findings_for_examination",
    "get_indications_for_examination",
    "get_indication_choices",
    "get_instruments_for_examination",
    "get_interventions_for_examination",
    "FindingViewSet",
    "get_interventions_for_finding",
    "get_classifications_for_finding",
    "FindingClassificationViewSet",
    "get_classification_choices",
    "get_morphology_choices",
    "get_location_choices",
    "CenterViewSet",
    "application_settings_detail",
    "application_settings_backup",
    "application_settings_centers_dropdown",
    "application_settings_processors_dropdown",
    "application_settings_annotators_dropdown",
    "application_settings_report_templates_dropdown",
    "application_settings_ai_datasets_dropdown",
    "application_settings_ai_dataset_attachments",
    "application_settings_ai_dataset_frame_bucket_distribution",
    "application_settings_ai_dataset_training_manifest",
    "application_settings_model_training_options",
    "application_settings_model_training_runs",
    "application_settings_model_training_run_detail",
    "application_settings_video_dimension_backfill_runs",
    "application_settings_video_dimension_backfill_run_detail",
    "application_settings_ai_dataset_export",
    "application_settings_ai_dataset_export_download",
    "application_settings_network_nodes",
    "application_settings_network_node_detail",
    "application_settings_network_node_roles_dropdown",
    "csrf_token_view",
    "GenderViewSet",
    "ExaminationStatsView",
    "VideoSegmentStatsView",
    "SensitiveMetaStatsView",
    "GeneralStatsView",
    "AuditLedgerIntegrityStatusView",
    "build_multilingual_response",
    "UploadFileView",
    "UploadStatusView",
    "PatientViewSet",
    "ExaminationCreateView",
    "PatientExaminationDetailView",
    "PatientExaminationListView",
    "PatientExaminationViewSet",
    "PatientFindingViewSet",
    "OptimizedPatientFindingViewSet",
    "create_patient_finding_classification",
    "ReportReimportView",
    "ReportLlmJobStatusView",
    "ReportStreamView",
    "PatientExaminationReportViewSet",
    "VideoApplyMaskView",
    "VideoRemoveFramesView",
    "VideoCorrectionView",
    "VideoReimportView",
    "VideoStreamView",
    "VideoExaminationViewSet",
    "label_list",
    "get_sensitive_metadata_pk",
    "video_sensitive_metadata",
    "video_sensitive_metadata_verify",
    "pdf_sensitive_metadata",
    "pdf_sensitive_metadata_verify",
    "sensitive_metadata_list",
    "pdf_sensitive_metadata_list",
]


def __dir__():
    return sorted(set(globals()) | set(__all__))
