from __future__ import annotations

from typing import Any

from endoreg_db.models import AnonymExaminationReport, DocumentType, RawPdfFile

DOCUMENT_TYPE_VALUES = [
    "report_draft",
    "report_final",
    "histology_draft",
    "histology_final",
]


def document_type_description(name: str) -> str:
    return f"Autogenerated document type for {name.replace('_', ' ')}"


def ensure_document_types() -> dict[str, DocumentType]:
    document_types: dict[str, DocumentType] = {}
    for name in DOCUMENT_TYPE_VALUES:
        document_type, _ = DocumentType.objects.get_or_create(
            name=name,
            defaults={"description": document_type_description(name)},
        )
        document_types[name] = document_type
    return document_types


def resolve_report_text(pdf: RawPdfFile, payload: dict[str, Any] | None = None) -> str:
    payload_obj = payload or {}

    payload_text = payload_obj.get("anonymized_text")
    if isinstance(payload_text, str) and payload_text.strip():
        return payload_text

    if isinstance(pdf.anonymized_text, str) and pdf.anonymized_text.strip():
        return pdf.anonymized_text

    sensitive_meta = pdf.sensitive_meta
    if sensitive_meta and isinstance(sensitive_meta.anonymized_text, str):
        if sensitive_meta.anonymized_text.strip():
            return sensitive_meta.anonymized_text

    if isinstance(pdf.text, str):
        return pdf.text
    return ""


def resolve_pdf_document_type_name(
    pdf: RawPdfFile, document_type_name: str | None = None
) -> str:
    if document_type_name:
        return document_type_name

    raw_meta = pdf.raw_meta if isinstance(pdf.raw_meta, dict) else {}
    candidate = raw_meta.get("document_type")
    if isinstance(candidate, str) and candidate in DOCUMENT_TYPE_VALUES:
        return candidate

    return "report_draft"


def upsert_anonym_examination_report_from_pdf(
    *,
    pdf: RawPdfFile,
    payload: dict[str, Any] | None = None,
    document_type_name: str | None = None,
    validated_at_iso: str | None = None,
    source: str = "case_resolution",
) -> tuple[AnonymExaminationReport, bool]:
    document_type = ensure_document_types()[
        resolve_pdf_document_type_name(pdf, document_type_name=document_type_name)
    ]
    sensitive_meta = pdf.sensitive_meta

    patient_examination = pdf.examination
    if patient_examination is None and sensitive_meta is not None:
        patient_examination = sensitive_meta.pseudo_examination

    patient = pdf.patient
    if patient is None and patient_examination is not None:
        patient = patient_examination.patient
    if patient is None and sensitive_meta is not None:
        patient = sensitive_meta.pseudo_patient

    center = pdf.center
    if center is None and sensitive_meta is not None:
        center = sensitive_meta.center

    report_obj = pdf.anonym_examination_report
    created = False
    if report_obj is None:
        report_obj = AnonymExaminationReport()
        created = True

    resolved_text = resolve_report_text(pdf, payload)

    report_obj.patient = patient
    report_obj.patient_examination = patient_examination
    report_obj.center = center
    report_obj.sensitive_meta = sensitive_meta
    report_obj.type = document_type
    report_obj.text = resolved_text

    meta_obj: dict[str, Any]
    if isinstance(report_obj.meta, dict):
        meta_obj = dict(report_obj.meta)
    else:
        meta_obj = {}
    meta_obj.update(
        {
            "source": source,
            "raw_pdf_file_id": pdf.pk,
            "document_type": document_type.name,
        }
    )
    if validated_at_iso is not None:
        meta_obj["validated_at"] = validated_at_iso
    report_obj.meta = meta_obj
    report_obj.save()

    update_fields: list[str] = []
    if pdf.anonym_examination_report_id != report_obj.id:
        pdf.anonym_examination_report = report_obj
        update_fields.append("anonym_examination_report")
    if getattr(pdf, "anonymized_text", None) != resolved_text:
        pdf.anonymized_text = resolved_text
        update_fields.append("anonymized_text")
    if pdf.center_id is None and center is not None:
        pdf.center = center
        update_fields.append("center")
    if update_fields:
        pdf.save(update_fields=update_fields)

    return report_obj, created


__all__ = [
    "DOCUMENT_TYPE_VALUES",
    "ensure_document_types",
    "resolve_report_text",
    "resolve_pdf_document_type_name",
    "upsert_anonym_examination_report_from_pdf",
]
