[build-system]
requires = ["maturin[zig]>=1.7,<2"]
build-backend = "maturin"

[project]
name = "endoreg_rust_backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

[tool.maturin]
module-name = "endoreg_rust_backend"
compatibility = "pypi"
zig = true
auditwheel = "repair"
features = ["pyo3/extension-module"]
