from django.urls import path

from endoreg_db.views import (
    application_settings_detail,
    application_settings_centers_dropdown,
    application_settings_processors_dropdown,
    application_settings_annotators_dropdown,
    application_settings_report_templates_dropdown,
    application_settings_ai_datasets_dropdown,
    application_settings_ai_dataset_frame_bucket_distribution,
    application_settings_model_training_options,
    application_settings_model_training_runs,
    application_settings_model_training_run_detail,
    application_settings_video_dimension_backfill_runs,
    application_settings_video_dimension_backfill_run_detail,
    application_settings_ai_dataset_export,
    application_settings_backup,
    application_settings_network_nodes,
    application_settings_network_node_detail,
    application_settings_network_node_roles_dropdown,
)

urlpatterns = [
    path(
        "settings/application/",
        application_settings_detail,
        name="application_settings_detail",
    ),
    path(
        "settings/application/dropdowns/centers/",
        application_settings_centers_dropdown,
        name="application_settings_centers_dropdown",
    ),
    path(
        "settings/application/dropdowns/processors/",
        application_settings_processors_dropdown,
        name="application_settings_processors_dropdown",
    ),
    path(
        "settings/application/dropdowns/annotators/",
        application_settings_annotators_dropdown,
        name="application_settings_annotators_dropdown",
    ),
    path(
        "settings/application/dropdowns/report_templates/",
        application_settings_report_templates_dropdown,
        name="application_settings_report_templates_dropdown",
    ),
    path(
        "settings/application/dropdowns/ai_datasets/",
        application_settings_ai_datasets_dropdown,
        name="application_settings_ai_datasets_dropdown",
    ),
    path(
        "settings/application/ai_datasets/<int:pk>/frame_bucket_distribution/",
        application_settings_ai_dataset_frame_bucket_distribution,
        name="application_settings_ai_dataset_frame_bucket_distribution",
    ),
    path(
        "settings/application/model_training/options/",
        application_settings_model_training_options,
        name="application_settings_model_training_options",
    ),
    path(
        "settings/application/model_training/runs/",
        application_settings_model_training_runs,
        name="application_settings_model_training_runs",
    ),
    path(
        "settings/application/model_training/runs/<str:run_id>/",
        application_settings_model_training_run_detail,
        name="application_settings_model_training_run_detail",
    ),
    path(
        "settings/application/video_dimension_backfill/runs/",
        application_settings_video_dimension_backfill_runs,
        name="application_settings_video_dimension_backfill_runs",
    ),
    path(
        "settings/application/video_dimension_backfill/runs/<str:run_id>/",
        application_settings_video_dimension_backfill_run_detail,
        name="application_settings_video_dimension_backfill_run_detail",
    ),
    path(
        "settings/application/ai_dataset_export/",
        application_settings_ai_dataset_export,
        name="application_settings_ai_dataset_export",
    ),
    path(
        "settings/application/backup/",
        application_settings_backup,
        name="application_settings_backup",
    ),
    path(
        "settings/application/network_nodes/",
        application_settings_network_nodes,
        name="application_settings_network_nodes",
    ),
    path(
        "settings/application/network_nodes/<int:pk>/",
        application_settings_network_node_detail,
        name="application_settings_network_node_detail",
    ),
    path(
        "settings/application/dropdowns/network_node_roles/",
        application_settings_network_node_roles_dropdown,
        name="application_settings_network_node_roles_dropdown",
    ),
]
