import logging
from datetime import date as dt_date, datetime, time as dt_time
from typing import Any, Dict, cast

from django.db import transaction
from django.utils import timezone
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.views import APIView

from endoreg_db.models import (
    AnonymExaminationReport,
    DocumentType,
    RawPdfFile,
    VideoFile,
)
from endoreg_db.models.metadata import SensitiveMeta
from endoreg_db.serializers.anonymization import (
    REPORT_DOCUMENT_TYPE_CHOICES,
    SensitiveMetaValidateSerializer,
)
from endoreg_db.utils.permissions import EnvironmentAwarePermission
from endoreg_db.utils.operation_log import (
    record_operation,
    ACTION_ANONYMIZATION_VALIDATED,
    STATUS_PROCESSING,
    STATUS_ANONYMIZED,
)


logger = logging.getLogger(__name__)

DOCUMENT_TYPE_VALUES = [choice[0] for choice in REPORT_DOCUMENT_TYPE_CHOICES]


def _document_type_description(name: str) -> str:
    return f"Autogenerated document type for {name.replace('_', ' ')}"


def _ensure_document_types() -> dict[str, DocumentType]:
    document_types: dict[str, DocumentType] = {}
    for name in DOCUMENT_TYPE_VALUES:
        document_type, _ = DocumentType.objects.get_or_create(
            name=name,
            defaults={"description": _document_type_description(name)},
        )
        document_types[name] = document_type
    return document_types


def _resolve_report_text(pdf: RawPdfFile, payload: Dict[str, Any]) -> str:
    payload_text = payload.get("anonymized_text")
    if isinstance(payload_text, str) and payload_text.strip():
        return payload_text

    if isinstance(pdf.anonymized_text, str) and pdf.anonymized_text.strip():
        return pdf.anonymized_text

    sensitive_meta = pdf.sensitive_meta
    if sensitive_meta and isinstance(sensitive_meta.anonymized_text, str):
        if sensitive_meta.anonymized_text.strip():
            return sensitive_meta.anonymized_text

    if isinstance(pdf.text, str):
        return pdf.text
    return ""


def _upsert_validated_report_file(
    *,
    pdf: RawPdfFile,
    payload: Dict[str, Any],
    document_type_name: str,
    validated_at_iso: str,
) -> tuple[AnonymExaminationReport, bool]:
    document_type = _ensure_document_types()[document_type_name]
    sensitive_meta = pdf.sensitive_meta

    patient_examination = pdf.examination
    if patient_examination is None and sensitive_meta is not None:
        patient_examination = sensitive_meta.pseudo_examination

    patient = pdf.patient
    if patient is None and patient_examination is not None:
        patient = patient_examination.patient
    if patient is None and sensitive_meta is not None:
        patient = sensitive_meta.pseudo_patient

    center = pdf.center
    if center is None and sensitive_meta is not None:
        center = sensitive_meta.center

    report_obj = pdf.anonym_examination_report
    created = False
    if report_obj is None:
        report_obj = AnonymExaminationReport()
        created = True

    resolved_text = _resolve_report_text(pdf, payload)

    report_obj.patient = patient
    report_obj.patient_examination = patient_examination
    report_obj.center = center
    report_obj.sensitive_meta = sensitive_meta
    report_obj.type = document_type
    report_obj.text = resolved_text

    meta_obj: Dict[str, Any]
    if isinstance(report_obj.meta, dict):
        meta_obj = dict(report_obj.meta)
    else:
        meta_obj = {}
    meta_obj.update(
        {
            "source": "anonymization_validate",
            "raw_pdf_file_id": pdf.pk,
            "document_type": document_type_name,
            "validated_at": validated_at_iso,
        }
    )
    report_obj.meta = meta_obj
    report_obj.save()

    update_fields: list[str] = []
    if pdf.anonym_examination_report_id != report_obj.id:
        pdf.anonym_examination_report = report_obj
        update_fields.append("anonym_examination_report")
    if pdf.examination_id is None and patient_examination is not None:
        pdf.examination = patient_examination
        update_fields.append("examination")
    if pdf.patient_id is None and patient is not None:
        pdf.patient = patient
        update_fields.append("patient")
    if pdf.center_id is None and center is not None:
        pdf.center = center
        update_fields.append("center")
    if getattr(pdf, "anonymized_text", None) != resolved_text:
        pdf.anonymized_text = resolved_text
        update_fields.append("anonymized_text")
    if update_fields:
        pdf.save(update_fields=update_fields)

    return report_obj, created


@api_view(["GET"])
@permission_classes([EnvironmentAwarePermission])
def anonymization_document_types_dropdown(_request):
    _ensure_document_types()
    return Response(
        [{"value": value, "label": value} for value in DOCUMENT_TYPE_VALUES],
        status=status.HTTP_200_OK,
    )


def _state_status_value(state_obj: Any) -> str | None:
    """Return anonymization status as string if present, else None."""
    if state_obj is None:
        return None
    st = getattr(state_obj, "anonymization_status", None)
    if st is None:
        return None
    return str(getattr(st, "value", st))


def _preferred_validation_timestamp(payload: Dict[str, Any]) -> tuple[str, str]:
    """
    Prefer a manually supplied examination_date as the validation timestamp.

    Returns:
        (iso_timestamp, source)
    """
    exam_date = payload.get("examination_date")
    if isinstance(exam_date, datetime):
        if timezone.is_naive(exam_date):
            exam_date = timezone.make_aware(exam_date, timezone.get_current_timezone())
        return exam_date.isoformat(), "manual_examination_date"
    if isinstance(exam_date, dt_date):
        preferred_dt = timezone.make_aware(
            datetime.combine(exam_date, dt_time.min), timezone.get_current_timezone()
        )
        return preferred_dt.isoformat(), "manual_examination_date"

    now_iso = timezone.now().isoformat()
    return now_iso, "request_time"


def _validation_operation_meta(payload: Dict[str, Any]) -> Dict[str, Any]:
    timestamp, source = _preferred_validation_timestamp(payload)
    meta: Dict[str, Any] = {
        "timestamp": timestamp,
        "timestamp_source": source,
    }
    exam_date = payload.get("examination_date")
    if isinstance(exam_date, (dt_date, datetime)):
        if isinstance(exam_date, datetime):
            meta["examination_date"] = exam_date.date().isoformat()
        else:
            meta["examination_date"] = exam_date.isoformat()
    return meta


class AnonymizationValidateView(APIView):
    """
    POST /api/anonymization/<int:file_id>/validate/

    Validiert und aktualisiert SensitiveMeta-Felder für Videos oder reports.

    DATA HERE IS COMING FROM THE ANONYIZATION VALIDATION COMPONENT

    Body (Datumsfelder bevorzugt in deutschem Format DD.MM.YYYY; ISO YYYY-MM-DD ebenfalls akzeptiert):
    {
      "patient_first_name": "Max",
      "patient_last_name":  "Mustermann",
      "patient_dob":        "21.03.1994",      // DD.MM.YYYY bevorzugt
      "patient_gender":     "male"
      "examination_date":   "15.02.2024",      // DD.MM.YYYY bevorzugt

      "casenumber":         "12345",
      "anonymized_text":    "...",             // nur für reports; Videos ignorieren
      "is_verified":        true               // optional; default true
      "file_type":        "video"            // optional; "video" oder "pdf"; wenn nicht angegeben, wird zuerst Video, dann report versucht
      "center_name":       editedPatient.value.centerName || '',
      "external_id":       editedPatient.value.externalId || '',
      "external_id_origin":editedPatient.value.externalIdOrigin || '',
    }

    Rückwärtskompatibilität: ISO-Format (YYYY-MM-DD) wird ebenfalls akzeptiert.
    """

    @transaction.atomic
    def post(self, request, file_id: int):
        # Serializer-Validierung mit deutscher Datums-Priorität
        serializer = SensitiveMetaValidateSerializer(data=request.data or {})
        serializer.is_valid(raise_exception=True)
        validated_data = cast(Dict[str, Any], serializer.validated_data)
        payload: Dict[str, Any] = dict(validated_data)

        # Default ist_verified = True
        if "is_verified" not in payload:
            payload["is_verified"] = True

        file_type = payload.get("file_type")
        status_before = None
        operation_meta = _validation_operation_meta(payload)
        response_timestamp = operation_meta["timestamp"]

        with transaction.atomic():
            # Try Video first (unless explicitly requesting report)
            if file_type in (None, "video"):
                video = (
                    VideoFile.objects.select_related(
                        "center", "sensitive_meta", "state"
                    )
                    .filter(pk=file_id)
                    .first()
                )
                # TODO: The state for video will be none when no state is set and the state for pdf will always be none. After status needs to be inferred after calling the sensitive meta state update functions
                if video is not None:
                    prepared_payload = self._prepare_payload(payload, video)
                    try:
                        ok = video.validate_metadata_annotation(prepared_payload)
                    except Exception:  # pragma: no cover - defensive safety net
                        logger.exception("Video validation crashed for id=%s", file_id)
                        return Response(
                            {
                                "error": "Video validation encountered an unexpected error."
                            },
                            status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                        )

                    if not ok:
                        return Response(
                            {"error": "Video validation failed."},
                            status=status.HTTP_400_BAD_REQUEST,
                        )

                    # this is here for tests!
                    if video.sensitive_meta is None:
                        sm = SensitiveMeta.objects.create(center=video.center)
                        video.sensitive_meta = sm

                    video.save(update_fields=["sensitive_meta"])
                    video.sensitive_meta.get_or_create_state()
                    if video.sensitive_meta.state is not None:
                        video.sensitive_meta.state.refresh_from_db()
                        video.sensitive_meta.state.mark_dob_verified()
                        video.sensitive_meta.state.mark_names_verified()
                        video.sensitive_meta.create_anonymized_record()
                    else:
                        return Response(
                            {"message": "Video not validated, failed to create State."},
                            status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                        )

                    # Capture status prior to final state mutation for accurate logging.
                    status_before = _state_status_value(video.state)

                    if video.state is not None:
                        video.state.anonymized = True
                        video.state.save(update_fields=["anonymized"])
                        video.sensitive_meta.state.save()

                        # --- NEW: status AFTER validation ---
                    status_after = status_before
                    try:
                        if video.state is not None:
                            video.state.refresh_from_db()
                            status_after = (
                                _state_status_value(video.state) or status_after
                            )
                    except Exception:
                        logger.exception(
                            "Failed to read video anonymization_status after validation"
                        )

                    # --- write operation log ---
                    # TODO: update the function call bases on the status , once merged
                    record_operation(
                        request,
                        action=ACTION_ANONYMIZATION_VALIDATED,
                        resource_type="video",
                        resource_id=file_id,
                        status_before=status_before or STATUS_PROCESSING,
                        status_after=status_after or STATUS_ANONYMIZED,
                        meta=operation_meta,
                    )

                    return Response(
                        {
                            "message": "Video validated.",
                            "timestamp": response_timestamp,
                        },
                        status=status.HTTP_200_OK,
                    )

                if file_type == "video":
                    return Response(
                        {"error": f"Video {file_id} not found."},
                        status=status.HTTP_404_NOT_FOUND,
                    )

            # Then report (unless explicitly requesting Video)
            if file_type in (None, "pdf"):
                pdf = (
                    RawPdfFile.objects.select_related(
                        "center", "sensitive_meta", "state"
                    )
                    .filter(pk=file_id)
                    .first()
                )
                if pdf is not None:
                    document_type_name = payload.get("document_type")
                    if (
                        not isinstance(document_type_name, str)
                        or not document_type_name
                    ):
                        return Response(
                            {
                                "error": "document_type is required for pdf validation.",
                                "allowed_document_types": DOCUMENT_TYPE_VALUES,
                            },
                            status=status.HTTP_400_BAD_REQUEST,
                        )
                    if document_type_name not in DOCUMENT_TYPE_VALUES:
                        return Response(
                            {
                                "error": (
                                    f"Unsupported document_type '{document_type_name}'."
                                ),
                                "allowed_document_types": DOCUMENT_TYPE_VALUES,
                            },
                            status=status.HTTP_400_BAD_REQUEST,
                        )

                    status_before = _state_status_value(pdf.state)
                    prepared_payload = self._prepare_payload(payload, pdf)
                    try:
                        ok = pdf.validate_metadata_annotation(prepared_payload)
                    except Exception:  # pragma: no cover - defensive safety net
                        logger.exception("report validation crashed for id=%s", file_id)
                        return Response(
                            {
                                "error": "report validation encountered an unexpected error."
                            },
                            status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                        )

                    # sanity logging – but don't break flow
                    try:
                        assert pdf.sensitive_meta is not None
                        assert pdf.sensitive_meta.state is not None
                    except AssertionError as e:
                        logger.error("%s", e)

                    if not ok:
                        return Response(
                            {"error": "report validation failed."},
                            status=status.HTTP_400_BAD_REQUEST,
                        )
                    else:
                        report_file_obj, report_file_created = (
                            _upsert_validated_report_file(
                                pdf=pdf,
                                payload=prepared_payload,
                                document_type_name=document_type_name,
                                validated_at_iso=response_timestamp,
                            )
                        )

                        # this is here for tests!
                        if pdf.sensitive_meta is None:
                            sm = SensitiveMeta.objects.create(center=pdf.center)
                            pdf.sensitive_meta = sm

                        pdf.save(update_fields=["sensitive_meta"])
                        pdf.sensitive_meta.get_or_create_state()
                        if pdf.sensitive_meta and pdf.sensitive_meta.state:
                            state_obj = cast(Any, pdf.sensitive_meta.state)
                            state_obj.refresh_from_db()
                            state_obj.mark_dob_verified()
                            state_obj.mark_names_verified()
                            pdf.sensitive_meta.create_anonymized_record()

                            if pdf.state:
                                pdf.state.mark_anonymized()
                                pdf.state.save(update_fields=["anonymized"])

                            state_obj.save()
                        else:
                            return Response(
                                {
                                    "message": "report not validated, failed to create State."
                                },
                                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                            )

                    status_after = status_before
                    try:
                        if pdf.state is not None:
                            pdf.state.refresh_from_db()
                            status_after = (
                                _state_status_value(pdf.state) or status_after
                            )
                    except Exception:
                        logger.exception(
                            "Failed to read pdf anonymization_status after validation"
                        )

                    # --- NEW: write operation log ---
                    record_operation(
                        request,
                        action=ACTION_ANONYMIZATION_VALIDATED,
                        resource_type="pdf",
                        resource_id=file_id,
                        status_before=status_before or STATUS_PROCESSING,
                        status_after=status_after or STATUS_ANONYMIZED,
                        meta=operation_meta,
                    )

                    return Response(
                        {
                            "message": "report validated.",
                            "timestamp": response_timestamp,
                            "report_file": {
                                "id": report_file_obj.id,
                                "document_type": document_type_name,
                                "created": report_file_created,
                            },
                        },
                        status=status.HTTP_200_OK,
                    )

                if file_type == "pdf":
                    return Response(
                        {"error": f"report {file_id} not found."},
                        status=status.HTTP_404_NOT_FOUND,
                    )

        return Response(
            {"error": f"Item {file_id} not found as video or pdf."},
            status=status.HTTP_404_NOT_FOUND,
        )

    @staticmethod
    def _prepare_payload(base_payload: Dict[str, Any], file_obj: Any) -> Dict[str, Any]:
        """
        Return a fresh payload tailored for the given file object.

        - Strips `file_type` before forwarding to validators.
        - Injects `center_name` from the file's center if not already present.
        - Normalizes `patient_gender` if present, but does NOT require it.
        """
        prepared: Dict[str, Any] = dict(base_payload)

        # never send file_type to validators
        prepared.pop("file_type", None)

        # center_name from file.center if not already set
        center = getattr(file_obj, "center", None)
        center_name = getattr(center, "name", None)
        if center_name and not prepared.get("center_name"):
            prepared["center_name"] = center_name

        # Gender normalization: optional, robust against missing or unknown values
        raw_gender = base_payload.get("patient_gender", None)
        if raw_gender is None:
            # nothing provided → don't touch gender
            return prepared

        gender = str(raw_gender).strip().lower()

        # empty string behaves as "not set" – don't override anything
        if gender == "":
            return prepared

        male_values = {"m", "male", "männlich"}
        female_values = {"w", "f", "female", "weiblich"}

        if gender in male_values:
            prepared["patient_gender"] = "male"
        elif gender in female_values:
            prepared["patient_gender"] = "female"
        else:
            # Unsupported values are ignored to prevent incorrect metadata coercion.
            logger.warning(
                "Unsupported patient_gender value %r; leaving value unchanged",
                raw_gender,
            )
            prepared.pop("patient_gender", None)

        return prepared
