# Generated by Django 5.1.6 on 2025-03-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='hash',
            field=models.CharField(default='asd', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensitivemeta',
            name='examiner_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensitivemeta',
            name='examiner_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensitivemeta',
            name='pseudo_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.patient'),
        ),
    ]
