# Generated by Django 5.1.6 on 2025-03-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpdffile',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_pdf_files', to='endoreg_db.reportfile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.center'),
        ),
    ]
