# Generated by Django 5.1.3 on 2024-11-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfinding',
            old_name='location_choices',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='patientfinding',
            old_name='morphology_choices',
            new_name='morphologies',
        ),
    ]
