# Generated by Django 5.2.4 on 2025-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpdfstate',
            name='pdf_meta_extracted',
            field=models.BooleanField(default=False, help_text='True if PDF metadata has been extracted.'),
        ),
    ]
