# Generated by Django 5.2.4 on 2025-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_rawpdfstate_pdf_meta_extracted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationindication',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='examinationindicationclassification',
            name='examination',
        ),
        migrations.AddField(
            model_name='examinationindication',
            name='examinations',
            field=models.ManyToManyField(blank=True, related_name='indications', to='endoreg_db.examination'),
        ),
        migrations.AddField(
            model_name='examinationindicationclassification',
            name='examinations',
            field=models.ManyToManyField(blank=True, related_name='indication_classifications', to='endoreg_db.examination'),
        ),
    ]
