# Generated by Django 5.2.5 on 2025-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_rawpdfstate_pdf_meta_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpdfstate',
            name='processing_error',
            field=models.BooleanField(default=False, help_text='True if an error occurred during processing.'),
        ),
        migrations.AddField(
            model_name='rawpdfstate',
            name='processing_started',
            field=models.BooleanField(default=False, help_text='True if the processing has started, but not yet completed.'),
        ),
        migrations.AddField(
            model_name='videostate',
            name='processing_started',
            field=models.BooleanField(default=False, help_text='True if the processing has started, but not yet completed.'),
        ),
    ]
