# Generated by Django 5.1.6 on 2025-03-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_rawpdffile_report_file_alter_patient_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpdffile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.center'),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.pdftype'),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_pdf_files', to='endoreg_db.reportfile'),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='sensitive_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_pdf_files', to='endoreg_db.sensitivemeta'),
        ),
        migrations.AlterField(
            model_name='rawvideofile',
            name='sensitive_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_videos', to='endoreg_db.sensitivemeta'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.center'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endoreg_db.examiner'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endoreg_db.patient'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='patient_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to='endoreg_db.patientexamination'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.pdftype'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='sensitive_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to='endoreg_db.sensitivemeta'),
        ),
    ]
