# Generated by Django 5.1.3 on 2024-11-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_findinglocationclassificationchoice_organ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFindingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories', models.JSONField(blank=True, null=True)),
                ('numerical_descriptors', models.JSONField(blank=True, null=True)),
                ('location_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_locations', to='endoreg_db.findinglocationclassificationchoice')),
                ('location_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_locations', to='endoreg_db.findinglocationclassification')),
            ],
            options={
                'verbose_name': 'Patient Finding Location',
                'verbose_name_plural': 'Patient Finding Locations',
                'ordering': ['location_classification', 'location_choice'],
            },
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='location_choices',
            field=models.ManyToManyField(blank=True, related_name='patient_findings', to='endoreg_db.patientfindinglocation'),
        ),
    ]
