# Generated by Django 5.1.6 on 2025-03-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_examiner_hash_sensitivemeta_examiner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivemeta',
            name='pseudo_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.patientexamination'),
        ),
    ]
