# Generated by Django 5.2.4 on 2025-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_informationsourcetype_alter_endoscopetype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsource',
            name='information_source_types',
            field=models.ManyToManyField(blank=True, related_name='information_sources', to='endoreg_db.informationsourcetype'),
        ),
    ]
