# Generated by Django 5.1.3 on 2024-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_rename_location_choices_patientfinding_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingmorphologyclassificationchoice',
            name='numerical_descriptors',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='findingmorphologyclassificationchoice',
            name='subcategories',
            field=models.JSONField(default=dict),
        ),
    ]
