# Generated by Django 5.1.6 on 2025-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0002_alter_frame_image_alter_rawframe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='db_frames'),
        ),
        migrations.AlterField(
            model_name='rawframe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='db_raw_frames'),
        ),
    ]
