# Generated by Django 5.2.5 on 2025-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_tag_requirementset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRequirementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_by_default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('examinations', models.ManyToManyField(blank=True, related_name='exam_reqset_links', to='endoreg_db.examination')),
            ],
        ),
        migrations.AddField(
            model_name='requirementset',
            name='reqset_exam_links',
            field=models.ManyToManyField(blank=True, related_name='requirement_set', to='endoreg_db.examinationrequirementset'),
        ),
    ]
