# Generated by Django 5.2 on 2025-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_labelvideosegment_patient_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='state_anonymous_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='state_anonymous_validated',
            field=models.BooleanField(default=False),
        ),
    ]
