# Generated by Django 4.2.11 on 2024-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_rawvideofile_frames_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawvideofile',
            old_name='hash',
            new_name='video_hash',
        ),
    ]
