# Generated by Django 5.1.3 on 2024-11-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_patientfindinglocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findinglocationclassificationchoice',
            name='organ',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_classification_choices', to='endoreg_db.organ'),
        ),
    ]
