# Generated by Django 5.1.6 on 2025-03-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_alter_rawpdffile_center_alter_rawpdffile_pdf_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='raw_meta',
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_videos', to='endoreg_db.video'),
        ),
    ]
