# Generated by Django 5.1.3 on 2024-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_alter_findingmorphologyclassificationchoice_numerical_descriptors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfindingintervention',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfindingintervention',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
