# Generated by Django 5.2.4 on 2025-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_remove_examinationindication_examination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='finding_classifications',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.findingclassification'),
        ),
    ]
