# Generated by Django 5.1.3 on 2025-04-21 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_anonymhistologyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationsource',
            options={'verbose_name': 'Information Source', 'verbose_name_plural': 'Information Sources'},
        ),
        migrations.AddField(
            model_name='informationsource',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='informationsource',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 4, 21, 19, 16, 4, 627145, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationsource',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='informationsource',
            index=models.Index(fields=['name'], name='endoreg_db__name_febac5_idx'),
        ),
        migrations.AddIndex(
            model_name='informationsource',
            index=models.Index(fields=['abbreviation'], name='endoreg_db__abbrevi_5a07c4_idx'),
        ),
    ]
