# Generated by Django 5.2.4 on 2025-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0003_alter_informationsource_information_source_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsource',
            name='information_source_types',
        ),
        migrations.AddField(
            model_name='informationsourcetype',
            name='information_sources',
            field=models.ManyToManyField(blank=True, related_name='information_source_types', to='endoreg_db.informationsource'),
        ),
    ]
