# Generated by Django 5.1.3 on 2025-04-22 17:26

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_alter_informationsource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymexaminationreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('data')), upload_to=pathlib.PurePosixPath('reports')),
        ),
        migrations.AlterField(
            model_name='anonymhistologyreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('data')), upload_to=pathlib.PurePosixPath('reports')),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('data')), upload_to=pathlib.PurePosixPath('raw_reports'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processed_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('data')), upload_to=pathlib.PurePosixPath('export/videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('data')), upload_to=pathlib.PurePosixPath('videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
