# Generated by Django 5.1.3 on 2024-11-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_patientfindingintervention_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfindingintervention',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_interventions', to='endoreg_db.findingintervention'),
        ),
    ]
