# Generated by Django 5.2 on 2025-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_rawvideofile_state_anonymous_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='endoscope_image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='endoscope_image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='endoscope_image_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='endoscope_image_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='suffix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
