# Generated by Django 5.1.6 on 2025-03-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_remove_reportfile_raw_meta_rawvideofile_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='raw_video',
        ),
    ]
