# Generated by Django 5.1.3 on 2024-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_alter_findinglocationclassificationchoice_organ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findinglocationclassificationchoice',
            name='organ',
        ),
        migrations.AddField(
            model_name='findinglocationclassificationchoice',
            name='organs',
            field=models.ManyToManyField(blank=True, related_name='location_choices', to='endoreg_db.organ'),
        ),
    ]
