# Generated by Django 5.2.4 on 2025-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0004_requirement_finding_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfindingintervention',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the intervention is currently active.'),
        ),
    ]
