# Generated by Django 5.2 on 2025-04-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0005_rawvideofile_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveMetaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frames_extracted', models.BooleanField(default=False)),
                ('initial_prediction', models.BooleanField(default=False)),
                ('lvs_created', models.BooleanField(default=False)),
                ('lvs_annotated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Video State',
                'verbose_name_plural': 'Video States',
            },
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_dob_substituted',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_endoscope_sn_substituted',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_examination_date_substituted',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_examiners_substituted',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_hash_generated',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_names_substituted',
        ),
        migrations.RemoveField(
            model_name='sensitivemeta',
            name='state_verified',
        ),
        migrations.CreateModel(
            name='LabelVideoSegmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction', models.BooleanField(default=False)),
                ('annotation', models.BooleanField(default=False)),
                ('frames_extracted', models.BooleanField(default=False)),
                ('origin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='endoreg_db.labelvideosegment')),
            ],
            options={
                'verbose_name': 'Label Video Segment State',
                'verbose_name_plural': 'Label Video Segment States',
            },
        ),
    ]
