# Generated by Django 5.1.3 on 2024-11-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0005_remove_findinglocationclassificationchoice_organ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findinglocationclassificationchoice',
            name='organs',
        ),
        migrations.AddField(
            model_name='organ',
            name='location_choices',
            field=models.ManyToManyField(blank=True, related_name='organs', to='endoreg_db.findinglocationclassificationchoice'),
        ),
    ]
