# Generated by Django 5.1.6 on 2025-03-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0006_alter_video_duration_alter_video_fps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pseudo_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='endoreg_db.patient'),
        ),
    ]
