# Generated by Django 5.1.3 on 2025-04-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0006_alter_anonymexaminationreport_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluserinfo',
            name='examiner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_user_info', to='endoreg_db.examiner'),
        ),
        migrations.AlterField(
            model_name='portaluserinfo',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_user_infos', to='endoreg_db.profession'),
        ),
    ]
