# Generated by Django 5.1.3 on 2024-11-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0006_remove_numericvaluedistribution_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoscope',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoscopes', to='endoreg_db.center'),
        ),
        migrations.AddField(
            model_name='endoscope',
            name='endoscopy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoscopes', to='endoreg_db.endoscopetype'),
        ),
        migrations.AddField(
            model_name='endoscopyprocessor',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoscopy_processors', to='endoreg_db.center'),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.center'),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.pdftype'),
        ),
    ]
