# Generated by Django 5.2 on 2025-04-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0006_sensitivemetastate_videostate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitivemetastate',
            options={'verbose_name': 'Sensitive Meta State', 'verbose_name_plural': 'Sensitive Meta States'},
        ),
        migrations.AddField(
            model_name='sensitivemetastate',
            name='dob_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensitivemetastate',
            name='names_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensitivemetastate',
            name='origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='endoreg_db.sensitivemeta'),
        ),
        migrations.AddField(
            model_name='videostate',
            name='origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='endoreg_db.video'),
        ),
    ]
