# Generated by Django 5.1.1 on 2024-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0006_alter_rawpdffile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='ping_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='ping_www',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='vpn_service_restart_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='vpn_service_restart_success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='vpn_service_status',
            field=models.BooleanField(default=False),
        ),
    ]
