# Generated by Django 5.1.6 on 2025-03-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_alter_video_pseudo_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='endoreg_db.patientexamination'),
        ),
    ]
