# Generated by Django 5.2 on 2025-04-19 13:03

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_alter_sensitivemetastate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_anonymized_frames_generated',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_censor_outside_completed',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_censor_outside_required',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_make_anonymized_video_completed',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_make_anonymized_video_required',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_ocr_completed',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_ocr_required',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_ocr_result_validated',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_outside_validated',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_sensitive_data_retrieved',
        ),
        migrations.AlterField(
            model_name='rawvideofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='data'), upload_to=pathlib.PurePosixPath('data/export/videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.CreateModel(
            name='RawVideoFileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frames_extracted', models.BooleanField(default=False)),
                ('initial_prediction', models.BooleanField(default=False)),
                ('lvs_created', models.BooleanField(default=False)),
                ('lvs_annotated', models.BooleanField(default=False)),
                ('origin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='endoreg_db.rawvideofile')),
            ],
            options={
                'verbose_name': 'Raw Video File State',
                'verbose_name_plural': 'Raw Video File States',
            },
        ),
    ]
