# Generated by Django 5.1.3 on 2025-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_portaluserinfo_examiner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelvideosegment',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='labelvideosegmentstate',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
