# Generated by Django 5.1.1 on 2024-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_networkdevicelogentry_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='aglnet_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkdevicelogentry',
            name='transferred_to_host',
            field=models.BooleanField(default=False),
        ),
    ]
