# Generated by Django 5.2 on 2025-04-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0007_alter_anonymexaminationreport_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('version_intern', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Information Source Type',
                'verbose_name_plural': 'Information Source Types',
                'unique_together': {('name', 'version_intern')},
            },
        ),
        migrations.AddField(
            model_name='informationsource',
            name='information_source_type',
            field=models.ForeignKey(blank=True, help_text='The type of this information source (e.g., guideline, chapter, recommendation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_sources', to='endoreg_db.informationsourcetype'),
        ),
    ]
