# Generated by Django 5.1.6 on 2025-03-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0008_video_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelvideosegment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_video_segments', to='endoreg_db.video'),
        ),
    ]
