# Generated by Django 5.1.3 on 2025-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0008_remove_labelvideosegment_is_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostate',
            name='frame_count',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number of frames of the video. This is optional and can be set later.', null=True),
        ),
    ]
