# Generated by Django 5.1.3 on 2024-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0008_contraindication_findinginterventiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingintervention',
            name='may_cause_findings',
        ),
        migrations.RemoveField(
            model_name='findingintervention',
            name='will_cause_findings',
        ),
        migrations.AddField(
            model_name='finding',
            name='causing_finding_interventions',
            field=models.ManyToManyField(blank=True, related_name='causing_findings', to='endoreg_db.findingintervention'),
        ),
        migrations.AddField(
            model_name='finding',
            name='opt_causing_finding_interventions',
            field=models.ManyToManyField(blank=True, related_name='opt_causing_findings', to='endoreg_db.findingintervention'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='finding_interventions',
            field=models.ManyToManyField(blank=True, related_name='findings', to='endoreg_db.findingintervention'),
        ),
    ]
