# Generated by Django 5.1.1 on 2024-10-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0009_alter_networkdevicelogentry_vpn_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevicelogentry',
            name='hostname',
        ),
    ]
