# Generated by Django 5.1.3 on 2024-11-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0009_remove_findingintervention_may_cause_findings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFindingIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.findingintervention')),
                ('patient_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='endoreg_db.patientfinding')),
            ],
        ),
    ]
