# Generated by Django 5.1.6 on 2025-03-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0009_alter_labelvideosegment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='sequences_model_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.modelmeta'),
        ),
        migrations.AddField(
            model_name='video',
            name='sequences_model_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.modelmeta'),
        ),
    ]
