# Generated by Django 5.1.3 on 2025-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0009_requirementoperator_requirementvaluetype_risktype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationindicationclassification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
