# Generated by Django 5.1.3 on 2024-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "endoreg_db",
            "0010_sensitivemeta_center_sensitivemeta_examination_hash_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rawvideofile",
            name="state_anonymized_frames_generated",
            field=models.BooleanField(default=False),
        ),
    ]
