# Generated by Django 4.2.11 on 2024-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0010_rename_endoscope_serial_number_sensitivemeta_endoscope_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='state_sensitive_data_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
