# Generated by Django 5.1.6 on 2025-03-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0010_rawvideofile_sequences_model_meta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawvideofile',
            old_name='sequences_model_meta',
            new_name='ai_model_meta',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='sequences_model_meta',
            new_name='ai_model_meta',
        ),
    ]
