# Generated by Django 5.1.3 on 2025-04-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0010_examinationindicationclassification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationindicationclassification',
            name='examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indication_classifications', to='endoreg_db.examination'),
        ),
    ]
