# Generated by Django 5.1.3 on 2025-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0010_alter_videostate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoimportmeta',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
