# Generated by Django 5.1.4 on 2024-12-09 08:45

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0011_rawvideofile_state_anonymized_frames_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawpdffile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/setup-user/luxnix-administration/erc_data"
                ),
                upload_to="raw_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rawvideofile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/setup-user/luxnix-administration/erc_data"
                ),
                upload_to="RAW_VIDEO_DIR_NAME",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
