# Generated by Django 5.2 on 2025-04-28 13:15

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0011_videoimportmeta_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymexaminationreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to=pathlib.PurePosixPath('pdfs')),
        ),
        migrations.AlterField(
            model_name='anonymhistologyreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to=pathlib.PurePosixPath('pdfs')),
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='weights',
            field=models.FileField(blank=True, help_text='Path to the model weights file (.ckpt), relative to MEDIA_ROOT.', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to='model_weights', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ckpt'])]),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to=pathlib.PurePosixPath('raw_pdfs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processed_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to=pathlib.PurePosixPath('export/videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/admin/dev/endoreg-db/data')), upload_to=pathlib.PurePosixPath('videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
