# Generated by Django 5.1.6 on 2025-03-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0011_rename_sequences_model_meta_rawvideofile_ai_model_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frames'),
        ),
        migrations.AlterField(
            model_name='labelvideosegment',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.label'),
        ),
        migrations.AlterField(
            model_name='labelvideosegment',
            name='prediction_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_segments', to='endoreg_db.videopredictionmeta'),
        ),
        migrations.AlterField(
            model_name='labelvideosegment',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.informationsource'),
        ),
    ]
