# Generated by Django 5.1.3 on 2025-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0011_examinationindicationclassification_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationindication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
