# Generated by Django 5.1.3 on 2025-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0012_examinationindication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationindication',
            name='expected_interventions',
            field=models.ManyToManyField(blank=True, related_name='indications', to='endoreg_db.findingintervention'),
        ),
    ]
