# Generated by Django 5.2 on 2025-05-19 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0013_employeetype_qualification_qualificationtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_type', models.CharField(max_length=80)),
                ('object_pk', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=40)),
                ('data', models.JSONField()),
                ('prev_hash', models.CharField(editable=False, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['object_type', 'object_pk'], name='endoreg_db__object__41eca6_idx')],
            },
        ),
    ]
