# Generated by Django 5.1.6 on 2025-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0013_alter_labelvideosegment_prediction_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
    ]
