# Generated by Django 5.1.3 on 2025-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0013_examinationindication_expected_interventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='risk_value',
            field=models.FloatField(blank=True, help_text='Risk value for the risk. If not set, the risk is not used in calculations.', null=True),
        ),
    ]
