# Generated by Django 5.2 on 2025-05-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0014_auditledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diseases', to='endoreg_db.disease'),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='endoreg_db.patient'),
        ),
        migrations.DeleteModel(
            name='AuditLedger',
        ),
    ]
