# Generated by Django 5.2 on 2025-05-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0014_auditledger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLedger',
        ),
    ]
