# Generated by Django 5.2 on 2025-05-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0015_alter_patientdisease_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_events', to='endoreg_db.event'),
        ),
        migrations.AlterField(
            model_name='patientevent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='endoreg_db.patient'),
        ),
    ]
