# Generated by Django 5.1.3 on 2025-04-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0015_requirementsettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='required_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requirements', to='endoreg_db.event'),
        ),
    ]
