# Generated by Django 5.1.6 on 2025-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0015_alter_labelrawvideosegment_prediction_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideopredictionmeta',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videopredictionmeta',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
    ]
