# Generated by Django 6.0 on 2026-04-16 16:04

import endoreg_db.models.media.video.storage_mode
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0016_uploadjob_content_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="storage_mode",
            field=models.CharField(
                choices=[
                    ("app_encrypted", "Application Encrypted"),
                    ("fs_encrypted_streamable", "Filesystem Encrypted Streamable"),
                ],
                default=endoreg_db.models.media.video.storage_mode.get_default_video_storage_mode_value,
                help_text="Controls whether this video stays on the legacy application-encrypted streaming path or may be handed off to Nginx from an encrypted filesystem-backed media root.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash", ""), _negated=True),
                fields=("source_center", "content_type", "content_hash"),
                name="uniq_uploadjob_content_hash_per_center_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=(
                    "source_center",
                    "source_system",
                    "ingest_mode",
                    "storage_class",
                    "storage_tier",
                    "idempotency_key",
                ),
                name="uniq_uploadjob_idempotency_key_scope",
            ),
        ),
    ]
