# Generated by Django 5.1.3 on 2025-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0016_requirement_required_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='required_event_count_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='required_event_count_min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
