# Generated by Django 5.1.6 on 2025-03-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0016_rawvideopredictionmeta_is_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
