# Generated by Django 5.1.6 on 2025-03-06 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0017_rawvideofile_duration_rawvideofile_fps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('suffix', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='frames')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='endoreg_db.rawvideofile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['video', 'frame_number'], name='endoreg_db__video_i_b5dc58_idx')],
                'unique_together': {('video', 'frame_number')},
            },
        ),
    ]
