# Generated by Django 5.2 on 2025-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0017_shift_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
