# Generated by Django 6.0 on 2026-04-16 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0017_alter_videofile_storage_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uploadjob",
            name="uniq_uploadjob_content_hash_per_center_type",
        ),
        migrations.RemoveConstraint(
            model_name="uploadjob",
            name="uniq_uploadjob_idempotency_key_scope",
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("content_hash", ""), _negated=True),
                    models.Q(("status__in", ["error", "lost"]), _negated=True),
                ),
                fields=("source_center", "content_type", "content_hash"),
                name="uniq_uploadjob_content_hash_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("idempotency_key", ""), _negated=True),
                    models.Q(("status__in", ["error", "lost"]), _negated=True),
                ),
                fields=(
                    "source_center",
                    "source_system",
                    "ingest_mode",
                    "storage_class",
                    "storage_tier",
                    "idempotency_key",
                ),
                name="uniq_uploadjob_idempotency_scope_active",
            ),
        ),
    ]
