# Generated by Django 5.2 on 2025-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0018_employeetype_is_active_qualification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
