# Generated by Django 5.1.3 on 2025-04-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0018_requirementtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
