# Generated by Django 5.2 on 2025-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0019_qualificationtype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleddays',
            name='name',
            field=models.CharField(default='asd', help_text='Name of the scheduled days.', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleddays',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name of the scheduled days in German.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleddays',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name of the scheduled days in English.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
