# Generated by Django 5.2 on 2025-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0020_scheduleddays_name_scheduleddays_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementoperator',
            name='operator_function_path',
            field=models.CharField(blank=True, help_text='Path to the function that evaluates the requirement operator. If not set, the default operator function is used.', max_length=255, null=True),
        ),
    ]
