# Generated by Django 5.2 on 2025-05-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0015_delete_auditledger'),
        ('endoreg_db', '0021_requirementoperator_operator_function_path'),
    ]

    operations = [
    ]
