# Generated by Django 5.2 on 2025-05-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0021_requirementoperator_operator_function_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementoperator',
            name='operator_function_path',
        ),
    ]
