# Generated by Django 5.2 on 2025-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0022_remove_requirementoperator_operator_function_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='labvalue',
            name='bound_adjustment_factor',
            field=models.FloatField(default=0.1, help_text='Factor for adjusting bounds when generating increased/decreased values, e.g., 0.1 for 10%.'),
        ),
    ]
