# Generated by Django 5.2 on 2025-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0023_labvalue_bound_adjustment_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.medication'),
        ),
    ]
