# Generated by Django 5.1.5 on 2025-02-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0023_alter_rawpdffile_file_alter_rawvideofile_file'),
        ('endoreg_db', '0023_remove_endoscopyprocessor_center_and_more'),
    ]

    operations = [
    ]
