# Generated by Django 5.2 on 2025-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0024_requirement_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='medication_indications',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.medicationindication'),
        ),
    ]
