# Generated by Django 5.1.5 on 2025-02-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0024_alter_rawpdffile_file_alter_rawvideofile_file'),
        ('endoreg_db', '0025_alter_rawpdffile_file_alter_rawvideofile_file'),
    ]

    operations = [
    ]
