# Generated by Django 5.2 on 2025-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0025_requirement_medication_indications'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='medication_intake_times',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.medicationintaketime'),
        ),
    ]
