# Generated by Django 6.0.5 on 2026-05-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endoreg_db", "0006_frame_old_examination_id_operationlog"),
        ("endoreg_db", "0025_alter_rawpdffile_file_and_more"),
    ]

    operations = []
