# Generated by Django 5.1.6 on 2025-02-20 17:59

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0026_alter_rawvideofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilabelvideosegmentationmodel',
            name='metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.modelmeta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multilabelvideosegmentationmodel',
            name='weights',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='db_model_weights', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.ckpt'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawvideofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='raw_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
