# Generated by Django 5.2 on 2025-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0027_requirement_medication_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationintaketime',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
