# Generated by Django 5.1.6 on 2025-02-20 19:54

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0027_multilabelvideosegmentationmodel_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilabelvideosegmentationmodel',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='multilabelvideosegmentationmodel',
            name='version',
        ),
        migrations.RemoveField(
            model_name='multilabelvideosegmentationmodel',
            name='weights',
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='db_model_weights', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.ckpt'])]),
        ),
    ]
