# Generated by Django 6.0.5 on 2026-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0028_ai_operation_artifacts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="frameboxannotation",
            new_name="endoreg_db__frame_i_54216f_idx",
            old_name="endoreg_db__frame_i_1044f1_idx",
        ),
        migrations.RenameIndex(
            model_name="frameboxannotation",
            new_name="endoreg_db__frame_i_27e48c_idx",
            old_name="endoreg_db__frame_i_397b7f_idx",
        ),
        migrations.RenameIndex(
            model_name="frameboxannotation",
            new_name="endoreg_db__externa_c50e13_idx",
            old_name="endoreg_db__extern_9d1f58_idx",
        ),
        migrations.AlterField(
            model_name="videoprocessinghistory",
            name="operation",
            field=models.CharField(
                choices=[
                    ("mask_overlay", "Mask Overlay"),
                    ("frame_removal", "Frame Removal"),
                    ("analysis", "Sensitivity Analysis"),
                    ("reprocessing", "Full Reprocessing"),
                    ("ai_temporal_inference", "AI Temporal Inference"),
                ],
                help_text="Type of processing operation",
                max_length=50,
            ),
        ),
    ]
