# Generated by Django 5.1.6 on 2025-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0028_remove_multilabelvideosegmentationmodel_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmeta',
            name='type',
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='activation',
            field=models.CharField(default='sigmoid', max_length=255),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='axes',
            field=models.CharField(default='2,0,1', max_length=255),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='batchsize',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='mean',
            field=models.CharField(default='0.45211223,0.27139644,0.19264949', max_length=255),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='num_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='size_x',
            field=models.IntegerField(default=716),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='size_y',
            field=models.IntegerField(default=716),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='std',
            field=models.CharField(default='0.31418097,0.21088019,0.16059452', max_length=255),
        ),
        migrations.AlterField(
            model_name='multilabelvideosegmentationmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
