# Generated by Django 5.1.6 on 2025-02-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0029_remove_modelmeta_type_modelmeta_activation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('model_subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('video_segmentation_labels', models.ManyToManyField(related_name='models', to='endoreg_db.videosegmentationlabel')),
            ],
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='endoreg_db.aimodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoSegmentationLabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('labels', models.ManyToManyField(related_name='labelsets', to='endoreg_db.videosegmentationlabel')),
            ],
        ),
        migrations.DeleteModel(
            name='MultilabelVideoSegmentationModel',
        ),
    ]
