# Generated by Django 5.2 on 2025-06-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0029_requirementoperator_evaluation_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.gender'),
        ),
    ]
