# Generated by Django 6.0.5 on 2026-05-12 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0030_frameextractionrequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="frameextractionrequest",
            new_name="frame_extra_video_i_e672aa_idx",
            old_name="frame_extra_video_i_f515a6_idx",
        ),
        migrations.RenameIndex(
            model_name="frameextractionrequest",
            new_name="frame_extra_status_7c6393_idx",
            old_name="frame_extra_status_9685be_idx",
        ),
        migrations.RenameIndex(
            model_name="frameextractionrequest",
            new_name="frame_extra_task_id_566a3b_idx",
            old_name="frame_extra_task_id_882a74_idx",
        ),
    ]
