# Generated by Django 5.2 on 2025-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0030_requirement_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingmorphologyclassification',
            name='examinations',
            field=models.ManyToManyField(blank=True, related_name='morphology_classifications', to='endoreg_db.examination'),
        ),
        migrations.AddField(
            model_name='findingmorphologyclassification',
            name='finding_types',
            field=models.ManyToManyField(blank=True, related_name='morphology_classifications', to='endoreg_db.findingtype'),
        ),
        migrations.AddField(
            model_name='findingmorphologyclassification',
            name='findings',
            field=models.ManyToManyField(blank=True, related_name='morphology_classifications', to='endoreg_db.finding'),
        ),
    ]
