# Generated by Django 5.1.6 on 2025-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0030_aimodel_modelmeta_model_videosegmentationlabelset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationindication',
            old_name='classification_choices',
            new_name='disease_classification_choices',
        ),
    ]
