# Generated by Django 5.2 on 2025-06-08 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0031_findingmorphologyclassification_examinations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deaktiviert statt gelöscht für Audit-Trail'),
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientfinding',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patientfinding',
            index=models.Index(fields=['patient_examination', 'finding'], name='endoreg_db__patient_54869f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfinding',
            index=models.Index(fields=['patient_examination', 'is_active'], name='endoreg_db__patient_9359f8_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfinding',
            index=models.Index(fields=['created_at'], name='endoreg_db__created_b44d86_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfinding',
            index=models.Index(fields=['finding', 'is_active'], name='endoreg_db__finding_2f036b_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientfinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient_examination', 'finding'), name='unique_active_finding_per_examination'),
        ),
        migrations.AddConstraint(
            model_name='patientfinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False)), _connector='OR'), name='deactivation_fields_consistency'),
        ),
    ]
