# Generated by Django 5.1.6 on 2025-02-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0031_rename_classification_choices_medicationindication_disease_classification_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='video_segmentation_labels',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='video_segmentation_labelset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='endoreg_db.videosegmentationlabelset'),
        ),
    ]
