# Generated by Codex on 2026-05-19

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0032_applicationsettings_ai_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaOperationLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lease_type",
                    models.CharField(
                        choices=[
                            ("stream", "Active stream"),
                            ("segment_update", "Segment update"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_operation_leases",
                        to="endoreg_db.videofile",
                    ),
                ),
            ],
            options={
                "db_table": "media_operation_lease",
                "ordering": ["expires_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mediaoperationlease",
            index=models.Index(
                fields=["video", "lease_type", "expires_at"],
                name="media_opera_video_i_c4d71c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaoperationlease",
            index=models.Index(
                fields=["lease_type", "expires_at"],
                name="media_opera_lease_t_63ed8b_idx",
            ),
        ),
    ]
