# Generated by Django 5.1.6 on 2025-02-21 21:59

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0032_remove_aimodel_video_segmentation_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='db_model_weights', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ckpt'])]),
        ),
    ]
