# Generated by Django 5.1.6 on 2025-02-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0033_alter_modelmeta_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='active_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_model', to='endoreg_db.modelmeta'),
        ),
    ]
