# Generated by Django 5.2 on 2025-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0033_findingclassificationtype_findingclassification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingclassificationchoice',
            name='classification',
        ),
        migrations.AddField(
            model_name='findingclassificationchoice',
            name='classifications',
            field=models.ManyToManyField(related_name='choices', to='endoreg_db.findingclassification'),
        ),
    ]
