# Generated by Django 5.1.6 on 2025-02-22 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0035_rawvideofile_binary_smooth_merged_predictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='weights',
            field=models.FileField(blank=True, null=True, upload_to='db_model_weights', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ckpt'])]),
        ),
    ]
