# Generated by Django 5.2 on 2025-06-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0035_patientfindingclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfindingclassification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the classification is currently active.'),
        ),
        migrations.AlterField(
            model_name='patientfindingclassification',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='endoreg_db.patientfinding'),
        ),
    ]
