# Generated by Django 5.1.6 on 2025-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0036_alter_modelmeta_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='state_censor_outside_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='state_censor_outside_required',
            field=models.BooleanField(default=True),
        ),
    ]
