# Generated by Django 4.2.11 on 2024-06-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0036_alter_rawpdffile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationindication',
            name='sources',
            field=models.ManyToManyField(to='endoreg_db.informationsource'),
        ),
    ]
