# Generated by Django 5.2 on 2025-06-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0037_uploadjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJob',
        ),
    ]
