# Generated by Django 5.1.6 on 2025-02-24 05:17

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0037_rawvideofile_state_censor_outside_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawvideofile',
            old_name='state_anonym_video_performed',
            new_name='state_make_anonymized_video_completed',
        ),
        migrations.RenameField(
            model_name='rawvideofile',
            old_name='state_anonym_video_required',
            new_name='state_make_anonymized_video_required',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_anonymized_frames_generated',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_finalized',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_original_reports_deleted',
        ),
        migrations.RemoveField(
            model_name='rawvideofile',
            name='state_original_video_deleted',
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('original_file_name', models.CharField(max_length=255)),
                ('video_hash', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('frame_dir', models.CharField(max_length=255)),
                ('prediction_dir', models.CharField(max_length=255)),
                ('predictions', models.JSONField(default=dict)),
                ('readable_predictions', models.JSONField(default=dict)),
                ('merged_predictions', models.JSONField(default=dict)),
                ('smooth_merged_predictions', models.JSONField(default=dict)),
                ('binary_smooth_merged_predictions', models.JSONField(default=dict)),
                ('sequences', models.JSONField(default=dict)),
                ('state_frames_required', models.BooleanField(default=True)),
                ('state_frames_extracted', models.BooleanField(default=False)),
                ('state_initial_prediction_required', models.BooleanField(default=True)),
                ('state_initial_prediction_completed', models.BooleanField(default=False)),
                ('state_initial_prediction_import_required', models.BooleanField(default=True)),
                ('state_initial_prediction_import_completed', models.BooleanField(default=False)),
                ('state_histology_required', models.BooleanField(blank=True, null=True)),
                ('state_histology_available', models.BooleanField(default=False)),
                ('state_follow_up_intervention_required', models.BooleanField(blank=True, null=True)),
                ('state_follow_up_intervention_available', models.BooleanField(default=False)),
                ('state_dataset_complete', models.BooleanField(default=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.center')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.endoscopyprocessor')),
                ('raw_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='endoreg_db.rawvideofile')),
                ('sensitive_meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.sensitivemeta')),
                ('video_meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.videometa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='endoreg_db.videofile'),
        ),
    ]
