# Generated by Django 6.0.5 on 2026-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0037_report_llm_inference_job"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_error", False),
                    ("processing_started", False),
                    _connector="OR",
                ),
                name="videostate_failed_not_started",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("processing_error", False),
                    _connector="OR",
                ),
                name="videostate_ready_not_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("anonymization_validated", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_validation",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("outside_segments_removed", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_cleanup",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("segment_annotations_validated", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_segments",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("ready_for_export_at__isnull", False),
                    _connector="OR",
                ),
                name="videostate_ready_requires_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    models.Q(("ready_for_export_by", ""), _negated=True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    models.Q(("processed_file_sha256", ""), _negated=True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_sha",
            ),
        ),
    ]
