# Generated by Django 5.1.6 on 2025-02-24 06:02

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0038_rename_state_anonym_video_performed_rawvideofile_state_make_anonymized_video_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvideofile',
            name='state_anonymized_frames_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawvideofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
