# Generated by Django 6.0.5 on 2026-05-27 10:26

import django.core.validators
import endoreg_db.utils.encryption.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0038_videostate_transition_constraints"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportllminferencejob",
            new_name="report_llm__pdf_id_6995a6_idx",
            old_name="report_llm_pdf_oper_1bf524_idx",
        ),
        migrations.RenameIndex(
            model_name="reportllminferencejob",
            new_name="report_llm__upload__55849f_idx",
            old_name="report_llm_upload__a8ad25_idx",
        ),
        migrations.RenameIndex(
            model_name="reportllminferencejob",
            new_name="report_llm__queue_27d75f_idx",
            old_name="report_llm_queue_3c9126_idx",
        ),
        migrations.RenameIndex(
            model_name="reportllminferencejob",
            new_name="report_llm__status_188b9e_idx",
            old_name="report_llm_status_d09b28_idx",
        ),
        migrations.AlterField(
            model_name="videofile",
            name="processed_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="processed_videos_final",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
