# Generated by Django 5.2 on 2025-06-30 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0038_delete_uploadjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAnonymizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymization_level', models.CharField(choices=[('minimal', 'Minimal'), ('faces', 'Faces'), ('full', 'Full')], default='faces', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('processed_frames', models.IntegerField(default=0)),
                ('segments', models.ManyToManyField(blank=True, related_name='anonymization_requests', to='endoreg_db.labelvideosegment')),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_requests', to='endoreg_db.videofile')),
            ],
            options={
                'db_table': 'frame_anonymization_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.IntegerField()),
                ('timestamp_ms', models.IntegerField(help_text='Frame timestamp in milliseconds')),
                ('original_frame_path', models.CharField(max_length=500)),
                ('anonymized_frame_path', models.CharField(max_length=500)),
                ('download_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('download_expires_at', models.DateTimeField()),
                ('download_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('anonymization_metadata', models.JSONField(blank=True, help_text='Metadata about anonymization process (e.g., detected faces, anonymization method)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_frames', to='endoreg_db.labelvideosegment')),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_frames', to='endoreg_db.videofile')),
                ('anonymization_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_frames', to='endoreg_db.frameanonymizationrequest')),
            ],
            options={
                'db_table': 'anonymous_frame',
                'ordering': ['frame_number'],
            },
        ),
        migrations.AddIndex(
            model_name='frameanonymizationrequest',
            index=models.Index(fields=['status'], name='frame_anony_status_768c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='frameanonymizationrequest',
            index=models.Index(fields=['created_at'], name='frame_anony_created_e78769_idx'),
        ),
        migrations.AddIndex(
            model_name='frameanonymizationrequest',
            index=models.Index(fields=['video_file', 'status'], name='frame_anony_video_f_c0be92_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousframe',
            index=models.Index(fields=['anonymization_request', 'frame_number'], name='anonymous_f_anonymi_1d3087_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousframe',
            index=models.Index(fields=['video_file', 'frame_number'], name='anonymous_f_video_f_998b83_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousframe',
            index=models.Index(fields=['download_token'], name='anonymous_f_downloa_376d95_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousframe',
            index=models.Index(fields=['download_expires_at'], name='anonymous_f_downloa_587166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymousframe',
            unique_together={('anonymization_request', 'frame_number')},
        ),
    ]
