# Generated by Django 5.2 on 2025-07-02 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0039_frameanonymizationrequest_anonymousframe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the upload job', primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded file (PDF or video)', upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('anonymized', 'Anonymized'), ('error', 'Error')], default='pending', help_text='Current processing status of the upload', max_length=20)),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the uploaded file', max_length=100)),
                ('error_detail', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the upload job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the upload job was last updated')),
                ('sensitive_meta', models.ForeignKey(blank=True, help_text='Link to the created SensitiveMeta record after processing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.sensitivemeta')),
            ],
            options={
                'verbose_name': 'Upload Job',
                'verbose_name_plural': 'Upload Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
