# Generated by Django 5.1.6 on 2025-02-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0039_rawvideofile_state_anonymized_frames_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='time',
        ),
        migrations.AddField(
            model_name='rawvideofile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.patient'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endoreg_db.patient'),
        ),
    ]
