# Generated by Django 5.1.6 on 2025-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0040_remove_examination_date_remove_examination_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
