# Generated by Django 5.2 on 2025-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0040_uploadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostate',
            name='sensitive_meta_processed',
            field=models.BooleanField(default=False, help_text='True if the video has been fully processed, meaning a anonymized person was created.'),
        ),
    ]
