# Generated by Django 5.1.6 on 2025-03-03 12:51

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0041_patient_patient_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientexamination',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='text_anonymized',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportfile',
            name='patient_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='endoreg_db.patientexamination'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endoreg_db.pdftype'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='raw_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpdffile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/admin/test-data'), upload_to='raw_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
