# Generated by Django 5.2 on 2025-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0041_videostate_sensitive_meta_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpdffile',
            name='anonymized',
            field=models.BooleanField(default=False, help_text='True if the PDF has been anonymized.'),
        ),
    ]
