# Generated by Django 6.0.6 on 2026-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0042_videohlsartifact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientlabvalue",
            old_name="datetime",
            new_name="timestamp",
        ),
        migrations.RenameIndex(
            model_name="videohlsartifact",
            new_name="endoreg_db__video_i_b05550_idx",
            old_name="endoreg_db__video_i_3a06b0_idx",
        ),
        migrations.RenameIndex(
            model_name="videohlsartifact",
            new_name="endoreg_db__key_id_9f61a0_idx",
            old_name="endoreg_db__key_id_0bfdb5_idx",
        ),
        migrations.AlterField(
            model_name="case",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="The end date and time of the case.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="A hash value associated with the case when configured.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientfindingclassification",
            name="numerical_descriptors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="patientfindingclassification",
            name="subcategories",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
