# Generated by Django 5.2 on 2025-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0042_rawpdffile_anonymized'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostate',
            name='anonymization_validated',
            field=models.BooleanField(default=False, help_text='True if the anonymization process has been validated and confirmed.'),
        ),
        migrations.AddField(
            model_name='videostate',
            name='segment_annotations_created',
            field=models.BooleanField(default=False, help_text='True if segment annotations have been created from LabelVideoSegments.'),
        ),
        migrations.AddField(
            model_name='videostate',
            name='segment_annotations_validated',
            field=models.BooleanField(default=False, help_text='True if segment annotations have been validated.'),
        ),
        migrations.AddField(
            model_name='videostate',
            name='was_created',
            field=models.BooleanField(default=True, help_text='True if this state was created for the first time.'),
        ),
    ]
