# Generated by Django 4.2.11 on 2024-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0042_casetemplateruletype_casetemplaterulevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetemplatetype',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casetemplatetype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
