# Generated by Django 5.1.6 on 2025-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0042_remove_patientexamination_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexamination',
            name='hash',
            field=models.CharField(default='asdsadasdasd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
