# Generated by Django 5.2.4 on 2025-07-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0043_remove_frameanonymizationrequest_segments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfindinglocation',
            name='location_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_locations', to='endoreg_db.findingclassification'),
        ),
        migrations.AlterField(
            model_name='patientfindinglocation',
            name='location_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_locations', to='endoreg_db.findingclassificationchoice'),
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='finding_location_classification_choices',
        ),
        migrations.RemoveField(
            model_name='findingmorphologyclassification',
            name='classification_type',
        ),
        migrations.RemoveField(
            model_name='findingmorphologyclassification',
            name='examinations',
        ),
        migrations.RemoveField(
            model_name='findingmorphologyclassification',
            name='finding_types',
        ),
        migrations.RemoveField(
            model_name='findingmorphologyclassification',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='findingmorphologyclassificationchoice',
            name='classification',
        ),
        migrations.AlterField(
            model_name='patientfindingmorphology',
            name='morphology_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_morphologies', to='endoreg_db.findingclassification'),
        ),
        migrations.AlterField(
            model_name='patientfindingmorphology',
            name='morphology_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_finding_morphologies', to='endoreg_db.findingclassificationchoice'),
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='finding_morphology_classification_choices',
        ),
        migrations.RemoveField(
            model_name='findingclassification',
            name='classification_type',
        ),
        migrations.AddField(
            model_name='findingclassification',
            name='classification_types',
            field=models.ManyToManyField(to='endoreg_db.findingclassificationtype'),
        ),
        migrations.AddField(
            model_name='findingclassification',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingclassification',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingclassificationchoice',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingclassificationchoice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='finding_classification_choices',
            field=models.ManyToManyField(blank=True, related_name='required_in', to='endoreg_db.findingclassificationchoice'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='optional_morphology_classification_types',
            field=models.ManyToManyField(blank=True, related_name='optional_for_findings', to='endoreg_db.findingclassificationtype'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='required_morphology_classification_types',
            field=models.ManyToManyField(blank=True, related_name='required_by_findings', to='endoreg_db.findingclassificationtype'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='location_choices',
            field=models.ManyToManyField(blank=True, related_name='organs', to='endoreg_db.findingclassificationchoice'),
        ),
        migrations.DeleteModel(
            name='FindingLocationClassification',
        ),
        migrations.DeleteModel(
            name='FindingLocationClassificationChoice',
        ),
        migrations.DeleteModel(
            name='FindingMorphologyClassificationType',
        ),
        migrations.DeleteModel(
            name='FindingMorphologyClassification',
        ),
        migrations.DeleteModel(
            name='FindingMorphologyClassificationChoice',
        ),
    ]
