# Generated by Django 5.2 on 2025-07-15 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0043_videostate_anonymization_validated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('processing_anonymization', 'Processing Anonymization'), ('extracting_frames', 'Extracting Frames'), ('predicting_segments', 'Predicting Segments'), ('done', 'Done'), ('failed', 'Failed'), ('validated', 'Validated')], default='not_started', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_details', models.JSONField(blank=True, default=dict)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_tasks', to='endoreg_db.videofile')),
            ],
            options={
                'db_table': 'anonymization_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='anonymizati_status_79f4eb_idx'), models.Index(fields=['video_file', 'status'], name='anonymizati_video_f_75a7b6_idx'), models.Index(fields=['created_at'], name='anonymizati_created_45defd_idx')],
            },
        ),
    ]
