# Generated by Django 5.2.4 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0044_alter_patientfindinglocation_location_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingclassificationchoice',
            name='classifications',
        ),
        migrations.AddField(
            model_name='findingclassification',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='classifications', to='endoreg_db.findingclassificationchoice'),
        ),
    ]
