# Generated by Django 5.2.4 on 2025-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0045_remove_findingclassificationchoice_classifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfindingmorphology',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='patientfindingmorphology',
            name='morphology_choice',
        ),
        migrations.RemoveField(
            model_name='patientfindingmorphology',
            name='morphology_classification',
        ),
        migrations.AlterModelOptions(
            name='patientfindingclassification',
            options={'ordering': ['finding', 'classification', 'classification_choice'], 'verbose_name': 'Patient Finding Classification', 'verbose_name_plural': 'Patient Finding Classifications'},
        ),
        migrations.RemoveField(
            model_name='finding',
            name='causing_finding_interventions',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='opt_causing_finding_interventions',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='optional_morphology_classification_types',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='required_morphology_classification_types',
        ),
        migrations.AddField(
            model_name='patientfindingclassification',
            name='numerical_descriptors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfindingclassification',
            name='subcategories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PatientFindingLocation',
        ),
        migrations.DeleteModel(
            name='PatientFindingMorphology',
        ),
    ]
