# Generated by Django 4.2.11 on 2024-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0050_casetemplaterule_rule_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetemplaterule',
            name='calling_rules',
        ),
        migrations.AddField(
            model_name='casetemplaterule',
            name='chained_rules',
            field=models.ManyToManyField(related_name='calling_rules', to='endoreg_db.casetemplaterule'),
        ),
        migrations.AlterField(
            model_name='casetemplaterule',
            name='rule_values',
            field=models.ManyToManyField(blank=True, null=True, related_name='rules', to='endoreg_db.casetemplaterulevalue'),
        ),
    ]
