# Generated by Django 6.0.6 on 2026-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0055_hls_generation_state_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videohlsartifact",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("dispatch_failed", "Dispatch Failed"),
                    ("inconsistent_artifact", "Inconsistent Artifact"),
                    ("materialization_failed", "Materialization Failed"),
                    ("validation_failed", "Validation Failed"),
                    ("stale_attempt", "Stale Attempt"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
