# Generated by Django 6.0.6 on 2026-08-11 07:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0059_videohlsartifact_encoding_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="role",
            field=models.CharField(
                choices=[
                    ("central_hub", "Central Hub"),
                    ("site_node", "Site Node"),
                    ("storage_node", "Storage Node"),
                    ("standalone", "Standalone"),
                ],
                default="site_node",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="StorageNodeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_draining", models.BooleanField(default=False)),
                ("failure_domain", models.CharField(max_length=128)),
                ("residency_key", models.CharField(max_length=128)),
                ("placement_weight", models.PositiveIntegerField(default=100)),
                ("total_bytes", models.PositiveBigIntegerField()),
                ("filesystem_free_bytes", models.PositiveBigIntegerField()),
                ("policy_usable_bytes", models.PositiveBigIntegerField()),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("in_flight_bytes", models.PositiveBigIntegerField(default=0)),
                ("committed_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "cleanup_reclaimable_bytes",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("observed_at", models.DateTimeField()),
                ("observation_version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_state",
                        to="endoreg_db.networknode",
                    ),
                ),
            ],
            options={"ordering": ["node__node_key"]},
        ),
        migrations.CreateModel(
            name="StorageNodeCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "storage_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_rows",
                        to="endoreg_db.storagenodestate",
                    ),
                ),
            ],
            options={"ordering": ["storage_node_id", "artifact_kind"]},
        ),
        migrations.CreateModel(
            name="StorageReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_key", models.CharField(max_length=255)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("requested_bytes", models.PositiveBigIntegerField()),
                ("policy_version", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="endoreg_db.storagenodestate",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="StorageArtifactPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_key", models.CharField(max_length=255)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("replica", "Replica")],
                        default="primary",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("copying", "Copying"),
                            ("verified", "Verified"),
                            ("committed", "Committed"),
                            ("superseded", "Superseded"),
                            ("lost", "Lost"),
                            ("failed", "Failed"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("expected_size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="endoreg_db.storagenodestate",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement",
                        to="endoreg_db.storagereservation",
                    ),
                ),
            ],
            options={"ordering": ["artifact_kind", "artifact_key", "generation", "pk"]},
        ),
        migrations.CreateModel(
            name="StorageRotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_key", models.CharField(max_length=255)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("initiated_by", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("copying", "Copying"),
                            ("copied", "Copied"),
                            ("verified", "Verified"),
                            ("committed", "Committed"),
                            ("cleanup_deferred", "Cleanup Deferred"),
                            ("cleaned", "Cleaned"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=24,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "terminal_failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("cleaned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_rotations",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
                (
                    "target_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_rotations",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.AddConstraint(
            model_name="storagenodestate",
            constraint=models.CheckConstraint(
                condition=models.Q(("placement_weight__gt", 0)),
                name="storage_node_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagenodestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("policy_usable_bytes__lte", models.F("total_bytes"))
                ),
                name="storage_usable_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagenodestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("filesystem_free_bytes__lte", models.F("total_bytes"))
                ),
                name="storage_free_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagenodestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reserved_bytes__lte",
                        models.F("policy_usable_bytes")
                        - models.F("in_flight_bytes")
                        - models.F("committed_bytes"),
                    )
                ),
                name="storage_accounted_within_usable",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagenodecapability",
            constraint=models.UniqueConstraint(
                fields=("storage_node", "artifact_kind"),
                name="unique_storage_node_capability",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagereservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_bytes__gt", 0)),
                name="storage_reservation_bytes_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagereservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("artifact_key", "artifact_kind"),
                name="unique_active_artifact_reservation",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageartifactplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gt", 0)),
                name="storage_placement_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageartifactplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size_bytes__gt", 0)),
                name="storage_placement_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageartifactplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary"), ("state", "committed")),
                fields=("artifact_key", "artifact_kind"),
                name="unique_committed_primary_placement",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageartifactplacement",
            constraint=models.UniqueConstraint(
                fields=("artifact_key", "artifact_kind", "storage_node", "generation"),
                name="unique_artifact_node_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagerotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_placement", models.F("target_placement")), _negated=True
                ),
                name="storage_rotation_distinct_placements",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagerotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size_bytes__gt", 0)),
                name="storage_rotation_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagerotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["cleaned", "failed"]), _negated=True),
                fields=("artifact_key", "artifact_kind"),
                name="unique_active_storage_rotation",
            ),
        ),
    ]
