# Generated by Django 6.0.6 on 2026-08-11 07:21

import hashlib
import json
import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_rotation_request_fingerprints(apps, schema_editor) -> None:
    storage_rotation = apps.get_model("endoreg_db", "StorageRotation")
    queryset = storage_rotation.objects.filter(request_fingerprint__isnull=True)
    for rotation in queryset.iterator(chunk_size=500):
        canonical = json.dumps(
            {
                "source_placement_id": str(rotation.source_placement_id),
                "target_placement_id": str(rotation.target_placement_id),
                "policy_version": rotation.policy_version,
                "initiated_by": rotation.initiated_by,
                "reason": rotation.reason,
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        rotation.request_fingerprint = hashlib.sha256(canonical).hexdigest()
        rotation.save(update_fields=["request_fingerprint"])


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0060_hub_storage_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagerotation",
            name="request_fingerprint",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RunPython(
            backfill_rotation_request_fingerprints,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="storagerotation",
            name="request_fingerprint",
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name="StorageRotationVerificationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_key", models.CharField(max_length=255)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_node_key", models.CharField(max_length=255)),
                ("expected_size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("placement_generation", models.PositiveBigIntegerField()),
                ("verifier", models.CharField(max_length=255)),
                ("evidence_reference", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("verified_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_receipt",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "target_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_receipts",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="StorageRotationCleanupReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_key", models.CharField(max_length=255)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("anonymized_video", "Anonymized Video"),
                            ("processed_report", "Processed Report"),
                            ("video_hls", "Video HTTP Live Streaming"),
                            ("streamable_video", "Streamable Video"),
                            ("sidecar", "Sidecar"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_node_key", models.CharField(max_length=255)),
                ("target_node_key", models.CharField(max_length=255)),
                ("expected_size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("placement_generation", models.PositiveBigIntegerField()),
                ("reconciler", models.CharField(max_length=255)),
                ("evidence_reference", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("media_leases_checked_at", models.DateTimeField()),
                ("replicas_checked_at", models.DateTimeField()),
                ("reconciled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanup_receipt",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "verification_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanup_receipts",
                        to="endoreg_db.storagerotationverificationreceipt",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="StorageReservationTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="endoreg_db.storagereservation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation", "target_status"),
                        name="unique_reservation_target_transition",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageRotationTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("copying", "Copying"),
                            ("copied", "Copied"),
                            ("verified", "Verified"),
                            ("committed", "Committed"),
                            ("cleanup_deferred", "Cleanup Deferred"),
                            ("cleaned", "Cleaned"),
                            ("failed", "Failed"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("copying", "Copying"),
                            ("copied", "Copied"),
                            ("verified", "Verified"),
                            ("committed", "Committed"),
                            ("cleanup_deferred", "Cleanup Deferred"),
                            ("cleaned", "Cleaned"),
                            ("failed", "Failed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "terminal_failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cleanup_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="endoreg_db.storagerotationcleanupreceipt",
                    ),
                ),
                (
                    "rotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "verification_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="endoreg_db.storagerotationverificationreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rotation", "target_state"),
                        name="unique_rotation_target_transition",
                    )
                ],
            },
        ),
    ]
