# Generated by Django 6.0.6 on 2026-08-11 07:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0061_storage_control_plane_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBalanceWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("drain", "Drain"),
                            ("capacity_pressure", "Capacity Pressure"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rotation_requested", "Rotation Requested"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("policy_version", models.CharField(max_length=64)),
                ("source_observation_version", models.PositiveBigIntegerField()),
                ("artifact_key", models.CharField(max_length=255)),
                ("artifact_kind", models.CharField(max_length=32)),
                ("expected_size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("placement_generation", models.PositiveBigIntegerField()),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "terminal_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_work_item",
                        to="endoreg_db.storagereservation",
                    ),
                ),
                (
                    "rotation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_work_item",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "source_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_work_items",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
                (
                    "target_placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_balance_work_items",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expected_size_bytes__gt", 0)),
                        name="balance_work_size_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("placement_generation__gt", 0)),
                        name="balance_work_generation_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reservation__isnull", False),
                                ("rotation__isnull", False),
                                ("status", "rotation_requested"),
                                ("target_placement__isnull", False),
                                ("terminal_reason", ""),
                            ),
                            models.Q(
                                ("reservation__isnull", True),
                                ("status", "blocked"),
                                ("rotation__isnull", True),
                                ("target_placement__isnull", True),
                                models.Q(("terminal_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="balance_work_status_payload_consistent",
                    ),
                ],
            },
        ),
    ]
