# Generated by Django 6.0.6 on 2026-08-11 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0062_storage_balance_work_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageTransferEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("envelope_generation", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("verified", "Verified"),
                            ("retired", "Retired"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                        ],
                        default="stored",
                        max_length=16,
                    ),
                ),
                ("node_key", models.CharField(max_length=253)),
                ("artifact_kind", models.CharField(max_length=32)),
                ("envelope_profile", models.CharField(max_length=64)),
                ("recipient_key_id", models.CharField(max_length=64)),
                ("plaintext_sha256", models.CharField(max_length=64)),
                ("plaintext_size", models.PositiveBigIntegerField()),
                ("ciphertext_sha256", models.CharField(max_length=64)),
                ("ciphertext_size", models.PositiveBigIntegerField()),
                (
                    "store_idempotency_key",
                    models.CharField(max_length=255, unique=True),
                ),
                ("store_request_fingerprint", models.CharField(max_length=64)),
                (
                    "verify_idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "verify_request_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("verifier", models.CharField(blank=True, default="", max_length=255)),
                (
                    "verification_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("stored_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_evidence",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
                (
                    "rotation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_transfer_evidence",
                        to="endoreg_db.storagerotation",
                    ),
                ),
            ],
            options={
                "ordering": ["placement_id", "envelope_generation", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("envelope_generation__gt", 0)),
                        name="storage_transfer_generation_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("plaintext_size__gt", 0), ("ciphertext_size__gt", 0)
                        ),
                        name="storage_transfer_sizes_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("placement", "envelope_generation"),
                        name="unique_placement_envelope_generation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "verified")),
                        fields=("placement",),
                        name="unique_verified_placement_envelope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deleted_at__isnull", True),
                                ("failure_reason", ""),
                                ("retired_at__isnull", True),
                                ("state", "stored"),
                                ("verification_reference", ""),
                                ("verified_at__isnull", True),
                                ("verifier", ""),
                                ("verify_idempotency_key__isnull", True),
                                ("verify_request_fingerprint", ""),
                            ),
                            models.Q(
                                ("deleted_at__isnull", True),
                                ("retired_at__isnull", True),
                                ("state", "verified"),
                                ("verified_at__isnull", False),
                                ("verify_idempotency_key__isnull", False),
                            ),
                            models.Q(
                                ("retired_at__isnull", False),
                                ("state", "retired"),
                                ("verified_at__isnull", False),
                            ),
                            models.Q(
                                ("deleted_at__isnull", False), ("state", "deleted")
                            ),
                            models.Q(
                                ("state", "failed"),
                                models.Q(("failure_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="storage_transfer_state_evidence_consistent",
                    ),
                ],
            },
        ),
    ]
