# Generated by Django 6.0.6 on 2026-08-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0063_storage_transfer_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagerotationverificationreceipt",
            name="transfer_evidence",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rotation_verification_receipt",
                to="endoreg_db.storagetransferevidence",
            ),
        ),
    ]
