# Generated by Django 6.0.6 on 2026-08-11 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0064_bind_rotation_transfer_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoragePlacementCommitReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="storagetransferevidence",
            name="storage_transfer_state_evidence_consistent",
        ),
        migrations.AddField(
            model_name="storagetransferevidence",
            name="retire_idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="storagetransferevidence",
            name="retire_request_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="storagetransferevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deleted_at__isnull", True),
                        ("failure_reason", ""),
                        ("retired_at__isnull", True),
                        ("state", "stored"),
                        ("verification_reference", ""),
                        ("verified_at__isnull", True),
                        ("verifier", ""),
                        ("verify_idempotency_key__isnull", True),
                        ("verify_request_fingerprint", ""),
                    ),
                    models.Q(
                        ("deleted_at__isnull", True),
                        ("retired_at__isnull", True),
                        ("state", "verified"),
                        ("verified_at__isnull", False),
                        ("verify_idempotency_key__isnull", False),
                    ),
                    models.Q(
                        ("retire_idempotency_key__isnull", False),
                        ("retired_at__isnull", False),
                        ("state", "retired"),
                        ("verified_at__isnull", False),
                    ),
                    models.Q(("deleted_at__isnull", False), ("state", "deleted")),
                    models.Q(
                        ("state", "failed"),
                        models.Q(("failure_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="storage_transfer_state_evidence_consistent",
            ),
        ),
        migrations.AddField(
            model_name="storageplacementcommitreceipt",
            name="placement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initial_commit_receipt",
                to="endoreg_db.storageartifactplacement",
            ),
        ),
        migrations.AddField(
            model_name="storageplacementcommitreceipt",
            name="transfer_evidence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placement_commit_receipt",
                to="endoreg_db.storagetransferevidence",
            ),
        ),
    ]
