# Generated by Django 6.0.6 on 2026-08-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0065_storage_transfer_commit_and_rekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageartifactplacement",
            name="media_lease_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_artifact_placements",
                to="endoreg_db.videofile",
            ),
        ),
    ]
