# Generated by Django 6.0.6 on 2026-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0067_storage_transfer_delete_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagenodestate",
            name="accepting_writes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagenodestate",
            name="is_reachable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagenodestate",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="storagenodestate",
            name="last_probe_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
