# Generated by Django 6.0.6 on 2026-08-11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0068_storage_node_probe_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBalanceCancellationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("rotation_from_state", models.CharField(max_length=24)),
                ("rotation_target_state", models.CharField(max_length=24)),
                ("reservation_from_status", models.CharField(max_length=16)),
                ("reservation_target_status", models.CharField(max_length=16)),
                ("cancelled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_cancellation_receipt",
                        to="endoreg_db.storagereservation",
                    ),
                ),
                (
                    "rotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_cancellation_receipt",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "work_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation_receipt",
                        to="endoreg_db.storagebalanceworkitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reservation_from_status", "active"),
                            ("reservation_target_status", "released"),
                            ("rotation_from_state", "requested"),
                            ("rotation_target_state", "failed"),
                        ),
                        name="balance_cancel_exact_compensation",
                    )
                ],
            },
        ),
    ]
