# Generated by Django 4.2.15 on 2024-08-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoreg_db', '0068_networkdevicetype_networkdevicetypemanager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkDeviceTypeManager',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
