# Generated by Django 6.0.6 on 2026-08-11 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0069_storage_balance_cancellation_receipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("requested_by", models.CharField(max_length=255)),
                (
                    "resume_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "next_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("observation_count", models.PositiveIntegerField()),
                ("discrepancy_count", models.PositiveIntegerField()),
                ("operational_event_count", models.PositiveIntegerField()),
                ("observed_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StorageReconciliationObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("artifact_key", models.CharField(max_length=255)),
                ("artifact_kind", models.CharField(max_length=32)),
                ("reachable", models.BooleanField()),
                ("remote_present", models.BooleanField()),
                ("remote_copy_count", models.PositiveIntegerField()),
                (
                    "remote_generation",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "remote_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "remote_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_observations",
                        to="endoreg_db.storageartifactplacement",
                    ),
                ),
                (
                    "storage_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_observations",
                        to="endoreg_db.storagenodestate",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="endoreg_db.storagereconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="StorageReconciliationOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("authorized_absence", "Authorized Absence"),
                            ("database_only", "Database Only"),
                            ("storage_only", "Storage Only"),
                            ("duplicate", "Duplicate"),
                            ("stale_generation", "Stale Generation"),
                            ("corrupt", "Corrupt"),
                            ("unreachable", "Unreachable"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "alert_code",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("storage_database_only", "Database-only artifact"),
                            ("storage_untracked_artifact", "Storage-only artifact"),
                            ("storage_duplicate_copy", "Duplicate storage copy"),
                            ("storage_stale_generation", "Stale generation"),
                            ("storage_integrity_mismatch", "Integrity mismatch"),
                            ("storage_node_unreachable", "Unreachable storage node"),
                            ("storage_health_stale", "Stale storage health"),
                            ("storage_capacity_low", "Low storage capacity"),
                            ("storage_capacity_stop", "Stop storage capacity"),
                            (
                                "storage_capacity_imbalance",
                                "Storage capacity imbalance",
                            ),
                            ("storage_rotation_stuck", "Stuck storage rotation"),
                            ("storage_reservation_expired", "Expired reservation"),
                            (
                                "storage_rotation_repeated_retry",
                                "Repeated rotation retry",
                            ),
                            ("storage_cleanup_failed", "Storage cleanup failure"),
                            (
                                "storage_only_verified_copy_lost",
                                "Only verified copy lost",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("correlation_id", models.CharField(max_length=255)),
                ("requires_operator_approval", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cleanup_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_outcomes",
                        to="endoreg_db.storagerotationcleanupreceipt",
                    ),
                ),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome",
                        to="endoreg_db.storagereconciliationobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StorageReconciliationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "alert_code",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("storage_database_only", "Database-only artifact"),
                            ("storage_untracked_artifact", "Storage-only artifact"),
                            ("storage_duplicate_copy", "Duplicate storage copy"),
                            ("storage_stale_generation", "Stale generation"),
                            ("storage_integrity_mismatch", "Integrity mismatch"),
                            ("storage_node_unreachable", "Unreachable storage node"),
                            ("storage_health_stale", "Stale storage health"),
                            ("storage_capacity_low", "Low storage capacity"),
                            ("storage_capacity_stop", "Stop storage capacity"),
                            (
                                "storage_capacity_imbalance",
                                "Storage capacity imbalance",
                            ),
                            ("storage_rotation_stuck", "Stuck storage rotation"),
                            ("storage_reservation_expired", "Expired reservation"),
                            (
                                "storage_rotation_repeated_retry",
                                "Repeated rotation retry",
                            ),
                            ("storage_cleanup_failed", "Storage cleanup failure"),
                            (
                                "storage_only_verified_copy_lost",
                                "Only verified copy lost",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("correlation_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_events",
                        to="endoreg_db.storagereservation",
                    ),
                ),
                (
                    "rotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_events",
                        to="endoreg_db.storagerotation",
                    ),
                ),
                (
                    "storage_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_events",
                        to="endoreg_db.storagenodestate",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_events",
                        to="endoreg_db.storagereconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="StorageHealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_count", models.PositiveIntegerField()),
                ("unreachable_node_count", models.PositiveIntegerField()),
                ("stale_health_count", models.PositiveIntegerField()),
                ("low_capacity_count", models.PositiveIntegerField()),
                ("stop_capacity_count", models.PositiveIntegerField()),
                ("critical_alert_count", models.PositiveIntegerField()),
                ("warning_alert_count", models.PositiveIntegerField()),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_snapshot",
                        to="endoreg_db.storagereconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="storagereconciliationobservation",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="unique_storage_reconciliation_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagereconciliationobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("remote_copy_count__gt", 0), ("remote_present", True)),
                    models.Q(
                        ("remote_copy_count", 0),
                        ("remote_generation__isnull", True),
                        ("remote_present", False),
                        ("remote_sha256", ""),
                        ("remote_size_bytes__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="storage_reconciliation_remote_payload_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagereconciliationevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="unique_storage_reconciliation_event_sequence",
            ),
        ),
    ]
